// County appraisal district public property search portals
// Used to look up official tax appraised values directly
// Format: "STATE:COUNTY" -> { searchUrl, searchType, notes }

export const COUNTY_PORTALS = {

  // ── TEXAS (254 counties) ──────────────────────────────────────────────────
  // Major metro counties
  "TX:Harris":        { searchUrl: "https://hcad.org/property-search/real-property/", name: "Harris County Appraisal District" },
  "TX:Dallas":        { searchUrl: "https://www.dallascad.org/SearchAddr.aspx", name: "Dallas Central Appraisal District" },
  "TX:Tarrant":       { searchUrl: "https://www.tad.org/property-search/", name: "Tarrant Appraisal District" },
  "TX:Bexar":         { searchUrl: "https://www.bcad.org/property-search/", name: "Bexar Appraisal District" },
  "TX:Travis":        { searchUrl: "https://travis.prodigycad.com/property-search", name: "Travis Central Appraisal District" },
  "TX:Collin":        { searchUrl: "https://www.collincad.org/propertysearch", name: "Collin Central Appraisal District" },
  "TX:Hidalgo":       { searchUrl: "https://www.hidalgoad.org/", name: "Hidalgo County Appraisal District" },
  "TX:El Paso":       { searchUrl: "https://www.epcad.org/property-search", name: "El Paso Central Appraisal District" },
  "TX:Denton":        { searchUrl: "https://www.dentoncad.com/property-search", name: "Denton Central Appraisal District" },
  "TX:Fort Bend":     { searchUrl: "https://www.fbcad.org/property-search/", name: "Fort Bend Central Appraisal District" },
  "TX:Montgomery":    { searchUrl: "https://mcad-tx.org/property-search/", name: "Montgomery Central Appraisal District" },
  "TX:Williamson":    { searchUrl: "https://www.wcad.org/property-search/", name: "Williamson Central Appraisal District" },
  "TX:Cameron":       { searchUrl: "https://www.cameroncad.org/", name: "Cameron County Appraisal District" },
  "TX:Nueces":        { searchUrl: "https://www.nuecescad.net/", name: "Nueces County Appraisal District" },
  "TX:Galveston":     { searchUrl: "https://www.galvestoncad.org/", name: "Galveston Central Appraisal District" },
  "TX:Brazoria":      { searchUrl: "https://www.brazoriacad.org/", name: "Brazoria County Appraisal District" },
  "TX:Bell":          { searchUrl: "https://www.bellcad.org/", name: "Bell County Appraisal District" },
  "TX:Webb":          { searchUrl: "https://www.webbcad.com/", name: "Webb County Appraisal District" },
  "TX:Lubbock":       { searchUrl: "https://www.lubbockcad.org/", name: "Lubbock Central Appraisal District" },
  "TX:Jefferson":     { searchUrl: "https://www.jcad.org/", name: "Jefferson County Appraisal District" },
  "TX:McLennan":      { searchUrl: "https://www.mclennancad.org/", name: "McLennan County Appraisal District" },
  "TX:Smith":         { searchUrl: "https://www.smithcad.org/", name: "Smith County Appraisal District" },
  "TX:Brazos":        { searchUrl: "https://www.brazoscad.org/", name: "Brazos Central Appraisal District" },
  "TX:Johnson":       { searchUrl: "https://www.johnsoncad.com/", name: "Johnson County Appraisal District" },
  "TX:Ellis":         { searchUrl: "https://www.elliscad.com/", name: "Ellis County Appraisal District" },
  "TX:Parker":        { searchUrl: "https://www.parkercad.org/", name: "Parker County Appraisal District" },
  "TX:Kaufman":       { searchUrl: "https://www.kaufmancad.org/", name: "Kaufman County Appraisal District" },
  "TX:Rockwall":      { searchUrl: "https://www.rockwallcad.com/", name: "Rockwall Central Appraisal District" },
  "TX:Hays":          { searchUrl: "https://hayscad.com/property-search/", name: "Hays Central Appraisal District" },
  "TX:Guadalupe":     { searchUrl: "https://www.guadalupecad.org/", name: "Guadalupe County Appraisal District" },
  "TX:Comal":         { searchUrl: "https://www.comalcad.org/", name: "Comal County Appraisal District" },
  "TX:Bastrop":       { searchUrl: "https://www.bastropcad.org/", name: "Bastrop County Appraisal District" },
  "TX:Taylor":        { searchUrl: "https://www.taylorcad.org/", name: "Taylor County Appraisal District" },
  "TX:Tom Green":     { searchUrl: "https://www.togreencad.com/", name: "Tom Green County Appraisal District" },
  "TX:Midland":       { searchUrl: "https://www.midlandcad.org/", name: "Midland Central Appraisal District" },
  "TX:Ector":         { searchUrl: "https://www.ectorcad.org/", name: "Ector County Appraisal District" },
  "TX:Wichita":       { searchUrl: "https://www.wichitacad.org/", name: "Wichita County Appraisal District" },
  "TX:Gregg":         { searchUrl: "https://www.greggcad.com/", name: "Gregg County Appraisal District" },
  "TX:Randall":       { searchUrl: "https://www.randallcad.com/", name: "Randall County Appraisal District" },
  "TX:Potter":        { searchUrl: "https://www.pottercad.org/", name: "Potter County Appraisal District" },
  "TX:Grayson":       { searchUrl: "https://www.graycad.org/", name: "Grayson Central Appraisal District" },
  "TX:Wise":          { searchUrl: "https://www.wisecad.net/", name: "Wise County Appraisal District" },
  "TX:Hood":          { searchUrl: "https://www.hoodcad.net/", name: "Hood County Appraisal District" },
  "TX:Henderson":     { searchUrl: "https://www.hendersoncad.org/", name: "Henderson County Appraisal District" },
  "TX:Hunt":          { searchUrl: "https://www.huntcad.com/", name: "Hunt County Appraisal District" },
  "TX:Navarro":       { searchUrl: "https://www.navarrocad.com/", name: "Navarro County Appraisal District" },
  "TX:Angelina":      { searchUrl: "https://www.angelinacad.org/", name: "Angelina County Appraisal District" },

  // ── GEORGIA (159 counties) ────────────────────────────────────────────────
  "GA:Fulton":        { searchUrl: "https://www.fultonassessor.org/", name: "Fulton County Board of Assessors" },
  "GA:Gwinnett":      { searchUrl: "https://www.gwinnettassessor.com/", name: "Gwinnett County Board of Assessors" },
  "GA:Cobb":          { searchUrl: "https://www.cobbtax.org/", name: "Cobb County Board of Tax Assessors" },
  "GA:DeKalb":        { searchUrl: "https://www.dekalbcountyga.gov/tax-assessors-office", name: "DeKalb County Board of Assessors" },
  "GA:Cherokee":      { searchUrl: "https://www.cherokeega.com/tax-assessors/", name: "Cherokee County Tax Assessors" },
  "GA:Forsyth":       { searchUrl: "https://www.forsythco.com/Departments-Offices/Board-of-Tax-Assessors", name: "Forsyth County Board of Assessors" },
  "GA:Hall":          { searchUrl: "https://www.hallcounty.org/228/Tax-Assessors", name: "Hall County Tax Assessors" },
  "GA:Henry":         { searchUrl: "https://www.hcboc.org/taxassessor", name: "Henry County Tax Assessors" },
  "GA:Paulding":      { searchUrl: "https://www.paulding.gov/352/Tax-Assessors", name: "Paulding County Tax Assessors" },
  "GA:Richmond":      { searchUrl: "https://www.augustaga.gov/183/Board-of-Assessors", name: "Richmond County Board of Assessors" },
  "GA:Columbia":      { searchUrl: "https://www.columbiacountyga.gov/county/tax-assessors-office", name: "Columbia County Tax Assessors" },
  "GA:Chatham":       { searchUrl: "https://www.chathamcounty.org/Departments/Board-of-Assessors", name: "Chatham County Board of Assessors" },
  "GA:Clayton":       { searchUrl: "https://www.claytoncountyga.gov/government/tax-assessors", name: "Clayton County Tax Assessors" },
  "GA:Muscogee":      { searchUrl: "https://www.columbusga.gov/board-of-tax-assessors/", name: "Muscogee County Board of Tax Assessors" },
  "GA:Bibb":          { searchUrl: "https://www.maconbibb.us/tax-assessors/", name: "Bibb County Tax Assessors" },
  "GA:Houston":       { searchUrl: "https://www.houstoncountyga.org/departments/tax-assessors.cms", name: "Houston County Tax Assessors" },
  "GA:Carroll":       { searchUrl: "https://www.carrollcountyga.com/145/Tax-Assessors", name: "Carroll County Tax Assessors" },
  "GA:Coweta":        { searchUrl: "https://www.coweta.ga.us/government/departments/tax-assessors", name: "Coweta County Tax Assessors" },
  "GA:Douglas":       { searchUrl: "https://www.celebratedouglas.com/government/tax-assessors/", name: "Douglas County Tax Assessors" },
  "GA:Fayette":       { searchUrl: "https://www.fayettecountyga.gov/tax_assessors/", name: "Fayette County Tax Assessors" },
  "GA:Lowndes":       { searchUrl: "https://www.lowndescounty.com/149/Tax-Assessors", name: "Lowndes County Tax Assessors" },
  "GA:Bartow":        { searchUrl: "https://www.bartowcountyga.gov/departments/tax_assessors/", name: "Bartow County Tax Assessors" },
  "GA:Spalding":      { searchUrl: "https://www.spaldingcounty.com/departments/tax-assessors/", name: "Spalding County Tax Assessors" },
  "GA:Whitfield":     { searchUrl: "https://www.whitfieldcountyga.com/tax-assessors/", name: "Whitfield County Tax Assessors" },
  "GA:Dougherty":     { searchUrl: "https://www.dougherty.ga.us/departments/tax_assessors/", name: "Dougherty County Tax Assessors" },
  "GA:Clarke":        { searchUrl: "https://www.accgov.com/tax-assessors", name: "Clarke County Tax Assessors" },
  "GA:Jackson":       { searchUrl: "https://www.jacksoncountyga.com/tax-assessors/", name: "Jackson County Tax Assessors" },
  "GA:Walton":        { searchUrl: "https://www.waltoncountyga.gov/departments/tax-assessors/", name: "Walton County Tax Assessors" },
  "GA:Newton":        { searchUrl: "https://www.newtoncountyga.gov/government/departments/tax_assessors/", name: "Newton County Tax Assessors" },
  "GA:Rockdale":      { searchUrl: "https://www.rockdalecountyga.gov/departments/tax-assessors/", name: "Rockdale County Tax Assessors" },

  // ── FLORIDA (67 counties) ─────────────────────────────────────────────────
  "FL:Miami-Dade":    { searchUrl: "https://www.miamidade.gov/pa/", name: "Miami-Dade County Property Appraiser" },
  "FL:Broward":       { searchUrl: "https://www.bcpa.net/", name: "Broward County Property Appraiser" },
  "FL:Palm Beach":    { searchUrl: "https://www.pbcgov.com/papa/", name: "Palm Beach County Property Appraiser" },
  "FL:Hillsborough":  { searchUrl: "https://www.hcpafl.org/", name: "Hillsborough County Property Appraiser" },
  "FL:Orange":        { searchUrl: "https://www.ocpafl.org/", name: "Orange County Property Appraiser" },
  "FL:Pinellas":      { searchUrl: "https://www.pcpao.gov/", name: "Pinellas County Property Appraiser" },
  "FL:Duval":         { searchUrl: "https://www.coj.net/departments/property-appraiser.aspx", name: "Duval County Property Appraiser" },
  "FL:Lee":           { searchUrl: "https://www.leepa.org/", name: "Lee County Property Appraiser" },
  "FL:Polk":          { searchUrl: "https://www.polkpa.org/", name: "Polk County Property Appraiser" },
  "FL:Brevard":       { searchUrl: "https://www.bcpao.us/", name: "Brevard County Property Appraiser" },
  "FL:Volusia":       { searchUrl: "https://vcpa.vcgov.org/", name: "Volusia County Property Appraiser" },
  "FL:Seminole":      { searchUrl: "https://www.scpafl.org/", name: "Seminole County Property Appraiser" },
  "FL:Pasco":         { searchUrl: "https://www.pascopa.com/", name: "Pasco County Property Appraiser" },
  "FL:Sarasota":      { searchUrl: "https://www.sc-pa.com/", name: "Sarasota County Property Appraiser" },
  "FL:Manatee":       { searchUrl: "https://www.manateepao.gov/", name: "Manatee County Property Appraiser" },
  "FL:Marion":        { searchUrl: "https://www.pa.marion.fl.us/", name: "Marion County Property Appraiser" },
  "FL:Collier":       { searchUrl: "https://www.collierappraiser.com/", name: "Collier County Property Appraiser" },
  "FL:Osceola":       { searchUrl: "https://www.property-appraiser.org/", name: "Osceola County Property Appraiser" },
  "FL:St. Lucie":     { searchUrl: "https://www.paslc.gov/", name: "St. Lucie County Property Appraiser" },
  "FL:Lake":          { searchUrl: "https://www.lakepa.org/", name: "Lake County Property Appraiser" },
  "FL:Escambia":      { searchUrl: "https://www.escpa.org/", name: "Escambia County Property Appraiser" },
  "FL:Leon":          { searchUrl: "https://www.leonpa.gov/", name: "Leon County Property Appraiser" },
  "FL:Alachua":       { searchUrl: "https://www.acpafl.org/", name: "Alachua County Property Appraiser" },
  "FL:Clay":          { searchUrl: "https://www.ccpao.com/", name: "Clay County Property Appraiser" },
  "FL:St. Johns":     { searchUrl: "https://www.sjcpa.us/", name: "St. Johns County Property Appraiser" },
  "FL:Indian River":  { searchUrl: "https://www.ircpa.org/", name: "Indian River County Property Appraiser" },
  "FL:Martin":        { searchUrl: "https://www.pa.martin.fl.us/", name: "Martin County Property Appraiser" },
  "FL:Charlotte":     { searchUrl: "https://www.ccappraiser.com/", name: "Charlotte County Property Appraiser" },
  "FL:Highlands":     { searchUrl: "https://www.hcpao.org/", name: "Highlands County Property Appraiser" },
  "FL:Hernando":      { searchUrl: "https://www.hernandopa.org/", name: "Hernando County Property Appraiser" },
  "FL:Citrus":        { searchUrl: "https://www.citruspa.org/", name: "Citrus County Property Appraiser" },
  "FL:Nassau":        { searchUrl: "https://www.nassauflpa.com/", name: "Nassau County Property Appraiser" },
  "FL:Bay":           { searchUrl: "https://www.baypa.net/", name: "Bay County Property Appraiser" },
  "FL:Okaloosa":      { searchUrl: "https://www.okaloosapa.com/", name: "Okaloosa County Property Appraiser" },
  "FL:Santa Rosa":    { searchUrl: "https://www.srcpa.org/", name: "Santa Rosa County Property Appraiser" },
  "FL:Flagler":       { searchUrl: "https://www.flaglerpa.com/", name: "Flagler County Property Appraiser" },
  "FL:Putnam":        { searchUrl: "https://www.putnam-fl.com/pa/", name: "Putnam County Property Appraiser" },
  "FL:Sumter":        { searchUrl: "https://www.sumterpa.com/", name: "Sumter County Property Appraiser" },
  "FL:Columbia":      { searchUrl: "https://www.columbiapafl.com/", name: "Columbia County Property Appraiser" },
  "FL:Suwannee":      { searchUrl: "https://www.suwanneepa.com/", name: "Suwannee County Property Appraiser" },
};

// Get portal info for a given state and county
export function getCountyPortal(stateCode, countyName) {
  if (!stateCode || !countyName) return null;
  const key = `${stateCode.toUpperCase()}:${countyName.replace(/ County$/i, "").trim()}`;
  return COUNTY_PORTALS[key] || null;
}
