// pages/api/sitemap.xml.js
// Self-contained sitemap — do not import from external files
// Updated: 2026-06-28 — 108 blog posts, all states

const floridaCitySlugs = [
  "miami-beach","coral-gables","coconut-grove","brickell","aventura","doral","kendall","hialeah",
  "boca-raton","fort-lauderdale","pompano-beach","hollywood-fl","weston","coral-springs","pembroke-pines","miramar",
  "west-palm-beach","boynton-beach","delray-beach","palm-beach-gardens","jupiter-fl","wellington-fl",
  "brandon-fl","riverview-fl","wesley-chapel","temple-terrace","lutz-fl",
  "clearwater-fl","st-petersburg-fl","largo-fl","dunedin-fl","tarpon-springs",
  "winter-park-fl","kissimmee-fl","oviedo-fl","lake-nona","apopka-fl",
  "naples-fl","marco-island","bonita-springs","fort-myers-fl","cape-coral","estero-fl",
  "sarasota-fl","venice-fl","north-port-fl",
  "jacksonville-beach","ponte-vedra-beach","fleming-island",
  "daytona-beach","new-smyrna-beach",
  "palm-beach","north-miami-beach","key-biscayne","lakeland-fl","hunters-creek-fl",
  "the-villages-fl","palm-bay-fl","port-st-lucie-fl","vero-beach-fl","pensacola-fl",
  "panama-city-beach-fl","tallahassee-fl","gainesville-fl","ocala-fl","st-augustine-fl",
  "deltona-fl","melbourne-fl","palm-coast-fl","santa-rosa-beach-fl","destin-fl",
  "bradenton-fl","punta-gorda-fl","port-charlotte-fl","crystal-river-fl","homosassa-fl",
  "fernandina-beach-fl","yulee-fl","land-o-lakes-fl","zephyrhills-fl","auburndale-fl",
  "haines-city-fl","celebration-fl","st-cloud-fl","poinciana-fl","dade-city-fl",
  "ormond-beach-fl","holly-hill-fl","edgewater-fl","new-port-richey-fl","tarpon-springs",
];

const allCountySlugs = [
  "anderson-county-tx",
  "andrews-county-tx",
  "angelina-county-tx",
  "aransas-county-tx",
  "archer-county-tx",
  "armstrong-county-tx",
  "atascosa-county-tx",
  "austin-county-tx",
  "bailey-county-tx",
  "bandera-county-tx",
  "bastrop-county-tx",
  "baylor-county-tx",
  "bee-county-tx",
  "bell-county-tx",
  "bexar-county-tx",
  "blanco-county-tx",
  "borden-county-tx",
  "bosque-county-tx",
  "bowie-county-tx",
  "brazoria-county-tx",
  "brazos-county-tx",
  "brewster-county-tx",
  "briscoe-county-tx",
  "brooks-county-tx",
  "brown-county-tx",
  "burleson-county-tx",
  "burnet-county-tx",
  "caldwell-county-tx",
  "calhoun-county-tx",
  "callahan-county-tx",
  "cameron-county-tx",
  "camp-county-tx",
  "carson-county-tx",
  "cass-county-tx",
  "castro-county-tx",
  "chambers-county-tx",
  "cherokee-county-tx",
  "childress-county-tx",
  "clay-county-tx",
  "cochran-county-tx",
  "coke-county-tx",
  "coleman-county-tx",
  "collin-county-tx",
  "collingsworth-county-tx",
  "colorado-county-tx",
  "comal-county-tx",
  "comanche-county-tx",
  "concho-county-tx",
  "cooke-county-tx",
  "coryell-county-tx",
  "cottle-county-tx",
  "crane-county-tx",
  "crockett-county-tx",
  "crosby-county-tx",
  "culberson-county-tx",
  "dallam-county-tx",
  "dallas-county-tx",
  "dawson-county-tx",
  "deaf-smith-county-tx",
  "delta-county-tx",
  "denton-county-tx",
  "dewitt-county-tx",
  "dickens-county-tx",
  "dimmit-county-tx",
  "donley-county-tx",
  "duval-county-tx",
  "eastland-county-tx",
  "ector-county-tx",
  "edwards-county-tx",
  "el-paso-county-tx",
  "ellis-county-tx",
  "erath-county-tx",
  "falls-county-tx",
  "fannin-county-tx",
  "fayette-county-tx",
  "fisher-county-tx",
  "floyd-county-tx",
  "foard-county-tx",
  "fort-bend-county-tx",
  "franklin-county-tx",
  "freestone-county-tx",
  "frio-county-tx",
  "gaines-county-tx",
  "galveston-county-tx",
  "garza-county-tx",
  "gillespie-county-tx",
  "glasscock-county-tx",
  "goliad-county-tx",
  "gonzales-county-tx",
  "gray-county-tx",
  "grayson-county-tx",
  "gregg-county-tx",
  "grimes-county-tx",
  "guadalupe-county-tx",
  "hale-county-tx",
  "hall-county-tx",
  "hamilton-county-tx",
  "hansford-county-tx",
  "hardeman-county-tx",
  "hardin-county-tx",
  "harris-county-tx",
  "harrison-county-tx",
  "hartley-county-tx",
  "haskell-county-tx",
  "hays-county-tx",
  "hemphill-county-tx",
  "henderson-county-tx",
  "hidalgo-county-tx",
  "hill-county-tx",
  "hockley-county-tx",
  "hood-county-tx",
  "hopkins-county-tx",
  "houston-county-tx",
  "howard-county-tx",
  "hudspeth-county-tx",
  "hunt-county-tx",
  "hutchinson-county-tx",
  "irion-county-tx",
  "jack-county-tx",
  "jackson-county-tx",
  "jasper-county-tx",
  "jeff-davis-county-tx",
  "jefferson-county-tx",
  "jim-hogg-county-tx",
  "jim-wells-county-tx",
  "johnson-county-tx",
  "jones-county-tx",
  "karnes-county-tx",
  "kaufman-county-tx",
  "kendall-county-tx",
  "kenedy-county-tx",
  "kent-county-tx",
  "kerr-county-tx",
  "kimble-county-tx",
  "king-county-tx",
  "kinney-county-tx",
  "kleberg-county-tx",
  "knox-county-tx",
  "la-salle-county-tx",
  "lamar-county-tx",
  "lamb-county-tx",
  "lampasas-county-tx",
  "lavaca-county-tx",
  "lee-county-tx",
  "leon-county-tx",
  "liberty-county-tx",
  "limestone-county-tx",
  "lipscomb-county-tx",
  "live-oak-county-tx",
  "llano-county-tx",
  "loving-county-tx",
  "lubbock-county-tx",
  "lynn-county-tx",
  "madison-county-tx",
  "marion-county-tx",
  "martin-county-tx",
  "mason-county-tx",
  "matagorda-county-tx",
  "maverick-county-tx",
  "mcculloch-county-tx",
  "mclennan-county-tx",
  "mcmullen-county-tx",
  "medina-county-tx",
  "menard-county-tx",
  "midland-county-tx",
  "milam-county-tx",
  "mills-county-tx",
  "mitchell-county-tx",
  "montague-county-tx",
  "montgomery-county-tx",
  "moore-county-tx",
  "morris-county-tx",
  "motley-county-tx",
  "nacogdoches-county-tx",
  "navarro-county-tx",
  "newton-county-tx",
  "nolan-county-tx",
  "nueces-county-tx",
  "ochiltree-county-tx",
  "oldham-county-tx",
  "orange-county-tx",
  "palo-pinto-county-tx",
  "panola-county-tx",
  "parker-county-tx",
  "parmer-county-tx",
  "pecos-county-tx",
  "polk-county-tx",
  "potter-county-tx",
  "presidio-county-tx",
  "rains-county-tx",
  "randall-county-tx",
  "reagan-county-tx",
  "real-county-tx",
  "red-river-county-tx",
  "reeves-county-tx",
  "refugio-county-tx",
  "roberts-county-tx",
  "robertson-county-tx",
  "rockwall-county-tx",
  "runnels-county-tx",
  "rusk-county-tx",
  "sabine-county-tx",
  "san-augustine-county-tx",
  "san-jacinto-county-tx",
  "san-patricio-county-tx",
  "san-saba-county-tx",
  "schleicher-county-tx",
  "scurry-county-tx",
  "shackelford-county-tx",
  "shelby-county-tx",
  "sherman-county-tx",
  "smith-county-tx",
  "somervell-county-tx",
  "starr-county-tx",
  "stephens-county-tx",
  "sterling-county-tx",
  "stonewall-county-tx",
  "sutton-county-tx",
  "swisher-county-tx",
  "tarrant-county-tx",
  "taylor-county-tx",
  "terrell-county-tx",
  "terry-county-tx",
  "throckmorton-county-tx",
  "titus-county-tx",
  "tom-green-county-tx",
  "travis-county-tx",
  "trinity-county-tx",
  "tyler-county-tx",
  "upshur-county-tx",
  "upton-county-tx",
  "uvalde-county-tx",
  "val-verde-county-tx",
  "van-zandt-county-tx",
  "victoria-county-tx",
  "walker-county-tx",
  "waller-county-tx",
  "ward-county-tx",
  "washington-county-tx",
  "webb-county-tx",
  "wharton-county-tx",
  "wheeler-county-tx",
  "wichita-county-tx",
  "wilbarger-county-tx",
  "willacy-county-tx",
  "williamson-county-tx",
  "wilson-county-tx",
  "winkler-county-tx",
  "wise-county-tx",
  "wood-county-tx",
  "yoakum-county-tx",
  "young-county-tx",
  "zapata-county-tx",
  "zavala-county-tx",
  "fulton-county-ga",
  "gwinnett-county-ga",
  "cobb-county-ga",
  "dekalb-county-ga",
  "cherokee-county-ga",
  "forsyth-county-ga",
  "henry-county-ga",
  "hall-county-ga",
  "richmond-county-ga",
  "bibb-county-ga",
  "columbia-county-ga",
  "muscogee-county-ga",
  "clayton-county-ga",
  "chatham-county-ga",
  "douglas-county-ga",
  "paulding-county-ga",
  "coweta-county-ga",
  "fayette-county-ga",
  "carroll-county-ga",
  "lowndes-county-ga",
  "newton-county-ga",
  "walton-county-ga",
  "bartow-county-ga",
  "rockdale-county-ga",
  "spalding-county-ga",
  "thomas-county-ga",
  "troup-county-ga",
  "whitfield-county-ga",
  "jackson-county-ga",
  "houston-county-ga",
  "gordon-county-ga",
  "catoosa-county-ga",
  "floyd-county-ga",
  "oconee-county-ga",
  "effingham-county-ga",
  "bryan-county-ga",
  "liberty-county-ga",
  "bulloch-county-ga",
  "glynn-county-ga",
  "dougherty-county-ga",
  "clarke-county-ga",
  "pickens-county-ga",
  "dawson-county-ga",
  "union-county-ga",
  "habersham-county-ga",
  "towns-county-ga",
  "elbert-county-ga",
  "haralson-county-ga",
  "upson-county-ga",
  "laurens-county-ga",
  "murray-county-ga",
  "miami-dade-county-fl",
  "broward-county-fl",
  "palm-beach-county-fl",
  "hillsborough-county-fl",
  "orange-county-fl",
  "pinellas-county-fl",
  "duval-county-fl",
  "polk-county-fl",
  "brevard-county-fl",
  "volusia-county-fl",
  "pasco-county-fl",
  "seminole-county-fl",
  "sarasota-county-fl",
  "lee-county-fl",
  "collier-county-fl",
  "manatee-county-fl",
  "marion-county-fl",
  "st-lucie-county-fl",
  "st-johns-county-fl",
  "lake-county-fl",
  "hernando-county-fl",
  "charlotte-county-fl",
  "osceola-county-fl",
  "indian-river-county-fl",
  "martin-county-fl",
  "alachua-county-fl",
  "leon-county-fl",
  "escambia-county-fl",
  "okaloosa-county-fl",
  "bay-county-fl",
  "citrus-county-fl",
  "clay-county-fl",
  "nassau-county-fl",
  "flagler-county-fl",
  "sumter-county-fl",
  "santa-rosa-county-fl",
  "walton-county-fl",
  "monroe-county-fl",
  "putnam-county-fl",
  "highlands-county-fl",
  "columbia-county-fl",
  "suwannee-county-fl",
  "okeechobee-county-fl",
  "wakulla-county-fl",
  "jefferson-county-fl",
  "taylor-county-fl",
  "hamilton-county-fl",
  "madison-county-fl",
  "lafayette-county-fl",
  "dixie-county-fl",
  "levy-county-fl",
  "gilchrist-county-fl",
  "baker-county-fl",
  "bradford-county-fl",
  "union-county-fl",
  "gulf-county-fl",
  "calhoun-county-fl",
  "jackson-county-fl",
  "washington-county-fl",
  "holmes-county-fl",
  "glades-county-fl",
  "hendry-county-fl",
  "desoto-county-fl",
  "hardee-county-fl",
  "franklin-county-fl",
  "gadsden-county-fl",
  "liberty-county-fl",
  "benton-county-ar",
  "pulaski-county-ar",
  "washington-county-ar",
  "sebastian-county-ar",
  "faulkner-county-ar",
  "saline-county-ar",
  "craighead-county-ar",
  "garland-county-ar",
  "white-county-ar",
  "lonoke-county-ar",
  "pope-county-ar",
  "jefferson-county-ar",
  "miller-county-ar",
  "crawford-county-ar",
  "crittenden-county-ar",
  "independence-county-ar",
  "mississippi-county-ar",
  "greene-county-ar",
  "union-county-ar",
  "hot-spring-county-ar",
  "boone-county-ar",
  "johnson-county-ar",
  "ouachita-county-ar",
  "van-buren-county-ar",
  "carroll-county-ar",
  // ── ALABAMA (67 counties) ──
  "jefferson-county-al","mobile-county-al","madison-county-al","shelby-county-al","montgomery-county-al",
  "tuscaloosa-county-al","lee-county-al","etowah-county-al","calhoun-county-al","morgan-county-al",
  "st-clair-county-al","elmore-county-al","houston-county-al","walker-county-al","limestone-county-al",
  "marshall-county-al","baldwin-county-al","talladega-county-al","jackson-county-al","russell-county-al",
  "dale-county-al","blount-county-al","cullman-county-al","cherokee-county-al","dekalb-county-al",
  "coffee-county-al","coosa-county-al","chilton-county-al","autauga-county-al","tallapoosa-county-al",
  "pickens-county-al","bibb-county-al","chambers-county-al","macon-county-al","monroe-county-al",
  "clarke-county-al","washington-county-al","winston-county-al","lawrence-county-al","sumter-county-al",
  "marengo-county-al","hale-county-al","perry-county-al","dallas-county-al","wilcox-county-al",
  "conecuh-county-al","escambia-county-al","covington-county-al","pike-county-al","barbour-county-al",
  "henry-county-al","geneva-county-al","cleburne-county-al","randolph-county-al","clay-county-al",
  "lamar-county-al","marion-county-al","fayette-county-al","choctaw-county-al","greene-county-al",
  "lowndes-county-al","bullock-county-al","crenshaw-county-al","butler-county-al",
];

const blogSlugs = [
  // ── TEXAS COUNTY GUIDES (25) ──
  "harris-county-property-tax-protest-guide-2026",
  "tarrant-county-property-tax-protest-guide-2026",
  "dallas-county-property-tax-protest-guide-2026",
  "travis-county-property-tax-protest-guide-2026",
  "bexar-county-property-tax-protest-guide-2026",
  "collin-county-property-tax-protest-guide-2026",
  "denton-county-property-tax-protest-guide-2026",
  "williamson-county-property-tax-protest-guide-2026",
  "montgomery-county-property-tax-protest-guide-2026",
  "fort-bend-county-property-tax-protest-guide-2026",
  "galveston-county-property-tax-protest-guide-2026",
  "el-paso-county-property-tax-protest-guide-2026",
  "hidalgo-county-property-tax-protest-guide-2026",
  "nueces-county-property-tax-protest-guide-2026",
  "mclennan-county-property-tax-protest-guide-2026",
  "hays-county-property-tax-protest-guide-2026",
  "bell-county-property-tax-protest-guide-2026",
  "brazoria-county-property-tax-protest-guide-2026",
  "smith-county-property-tax-protest-guide-2026",
  "jefferson-county-property-tax-protest-guide-2026",
  "lubbock-county-property-tax-protest-guide-2026",
  "parker-county-property-tax-protest-guide-2026",
  "cameron-county-property-tax-protest-guide-2026",
  "grayson-county-property-tax-protest-guide-2026",
  "tom-green-county-property-tax-protest-guide-2026",
  // ── TEXAS EDUCATION / STRATEGY (17) ──
  "texas-property-tax-protest-guide-2026",
  "texas-property-tax-protest-deadline-2026",
  "texas-property-tax-protest-letter-what-to-include",
  "how-to-read-texas-notice-of-appraised-value",
  "how-much-can-i-save-protesting-property-taxes-texas",
  "texas-homestead-exemption-vs-protest-which-saves-more",
  "flat-fee-vs-contingency-property-tax-protest",
  "property-tax-flat-fee-vs-contingency-texas-2026",
  "texas-arb-hearing-guide-2026",
  "texas-unequal-appraisal-protest-guide-2026",
  "texas-property-tax-protest-new-homeowner-guide-2026",
  "texas-property-tax-protest-evidence-checklist-2026",
  "texas-investment-property-tax-protest-guide-2026",
  "texas-mass-appraisal-errors-guide-2026",
  "ownwell-vs-taxappeal-usa-comparison-2026",
  "how-much-does-texas-property-tax-protest-cost-2026",
  "williamson-vs-travis-county-property-taxes-austin",
  // ── FLORIDA COUNTY GUIDES (26) ──
  "miami-dade-property-tax-appeal-guide-2026",
  "broward-county-property-tax-appeal-guide-2026",
  "palm-beach-county-property-tax-appeal-guide-2026",
  "hillsborough-county-property-tax-appeal-2026",
  "orange-county-florida-property-tax-appeal-guide-2026",
  "pinellas-county-florida-property-tax-appeal-guide-2026",
  "sarasota-county-florida-property-tax-appeal-guide-2026",
  "lee-county-florida-property-tax-appeal-guide-2026",
  "collier-county-florida-property-tax-appeal-guide-2026",
  "okaloosa-county-florida-property-tax-appeal-guide-2026",
  "duval-county-jacksonville-property-tax-appeal-guide-2026",
  "manatee-county-florida-property-tax-appeal-guide-2026",
  "pasco-county-florida-property-tax-appeal-guide-2026",
  "volusia-county-florida-property-tax-appeal-guide-2026",
  "brevard-county-florida-property-tax-appeal-guide-2026",
  "polk-county-florida-property-tax-appeal-guide-2026",
  "st-johns-county-florida-property-tax-appeal-guide-2026",
  "osceola-county-florida-property-tax-appeal-guide-2026",
  "st-lucie-county-florida-property-tax-appeal-guide-2026",
  "alachua-county-florida-property-tax-appeal-guide-2026",
  "escambia-county-florida-property-tax-appeal-guide-2026",
  "walton-county-florida-property-tax-appeal-guide-2026",
  "charlotte-county-florida-property-tax-appeal-guide-2026",
  "bay-county-florida-property-tax-appeal-guide-2026",
  "citrus-county-florida-property-tax-appeal-guide-2026",
  "nassau-county-florida-property-tax-appeal-guide-2026",
  // ── FLORIDA EDUCATION / STRATEGY (21) ──
  "how-to-appeal-florida-property-tax-trim-notice-guide",
  "florida-trim-notice-deadline-2026",
  "how-to-read-florida-trim-notice-2026",
  "when-do-florida-trim-notices-arrive-2026",
  "what-is-a-vab-petition-florida-homeowners-guide",
  "florida-vab-filing-fee-by-county-2026",
  "how-much-can-i-save-appealing-florida-property-tax",
  "florida-property-tax-appeal-letter-what-to-include-to-win",
  "florida-property-tax-appeal-success-rate",
  "do-i-need-a-lawyer-to-appeal-florida-property-taxes",
  "non-homestead-property-tax-appeal-florida",
  "save-our-homes-florida-can-you-still-appeal-property-taxes",
  "florida-homestead-exemption-vs-property-tax-appeal",
  "florida-property-tax-appeal-vs-homestead-exemption-which-saves-more",
  "florida-condo-property-tax-appeal-guide-2026",
  "florida-new-construction-property-tax-appeal-2026",
  "florida-property-tax-appeal-evidence-guide-2026",
  "florida-property-tax-appeal-comparable-sales-guide",
  "florida-first-time-property-tax-appeal-guide-2026",
  "florida-property-tax-appeal-deadline-missed-what-now",
  "miami-beach-luxury-property-tax-appeal-2026",
  // ── GEORGIA COUNTY GUIDES (18) ──
  "fulton-county-property-tax-appeal-guide-2026",
  "gwinnett-county-property-tax-appeal-guide-2026",
  "cobb-county-property-tax-appeal-guide-2026",
  "dekalb-county-property-tax-appeal-guide-2026",
  "cherokee-county-property-tax-appeal-guide-2026",
  "forsyth-county-georgia-property-tax-appeal-2026",
  "henry-county-georgia-property-tax-appeal-2026",
  "hall-county-georgia-property-tax-appeal-2026",
  "richmond-county-georgia-property-tax-appeal-2026",
  "paulding-county-georgia-property-tax-appeal-2026",
  "gwinnett-county-georgia-property-tax-appeal-deep-dive-2026",
  "douglas-county-georgia-property-tax-appeal-2026",
  "columbia-county-georgia-property-tax-appeal-2026",
  "muscogee-county-georgia-property-tax-appeal-2026",
  "bibb-county-georgia-property-tax-appeal-2026",
  "clayton-county-georgia-property-tax-appeal-2026",
  "carroll-county-georgia-property-tax-appeal-2026",
  "coweta-county-georgia-property-tax-appeal-2026",
  "savannah-chatham-county-georgia-property-tax-appeal-2026",
  "whitfield-county-georgia-property-tax-appeal-2026",
  "bartow-county-georgia-property-tax-appeal-2026",
  "newton-county-georgia-property-tax-appeal-2026",
  // ── GEORGIA EDUCATION / STRATEGY (17) ──
  "georgia-property-tax-appeal-deadline-2026",
  "how-to-read-georgia-notice-of-assessment-2026",
  "how-much-can-i-save-appealing-georgia-property-taxes",
  "georgia-property-tax-appeal-letter-what-to-include",
  "georgia-board-of-equalization-what-homeowners-need-to-know",
  "georgia-property-tax-appeal-complete-guide-2026",
  "atlanta-property-tax-appeal-neighborhood-guide-2026",
  "georgia-property-tax-appeal-evidence-guide-2026",
  "georgia-new-homeowner-property-tax-guide-2026",
  "georgia-investment-property-tax-appeal-2026",
  "georgia-first-time-property-tax-appeal-guide-2026",
  "georgia-condo-property-tax-appeal-2026",
  "georgia-missed-appeal-deadline-what-to-do-2026",
  "georgia-homestead-exemption-property-tax-guide-2026",
  "buckhead-sandy-springs-property-tax-appeal-2026",
  "georgia-new-construction-property-tax-appeal-2026",
  "georgia-property-tax-comparable-sales-guide-2026",
  // ── ARKANSAS COUNTY GUIDES (11) ──
  "benton-county-arkansas-property-tax-appeal-2026",
  "pulaski-county-arkansas-property-tax-appeal-2026",
  "washington-county-arkansas-property-tax-appeal-2026",
  "sebastian-county-arkansas-property-tax-appeal-2026",
  "faulkner-county-arkansas-property-tax-appeal-2026",
  "saline-county-arkansas-property-tax-appeal-2026",
  "garland-county-arkansas-property-tax-appeal-2026",
  "craighead-county-arkansas-property-tax-appeal-2026",
  "lonoke-county-arkansas-property-tax-appeal-2026",
  "pope-county-arkansas-property-tax-appeal-2026",
  "white-county-arkansas-property-tax-appeal-2026",
  // ── ARKANSAS EDUCATION / STRATEGY (14) ──
  "arkansas-property-tax-appeal-deadline-2026",
  "how-to-appeal-arkansas-property-taxes-board-of-equalization",
  "arkansas-property-tax-appeal-complete-guide-2026",
  "arkansas-property-tax-vs-other-states-2026",
  "northwest-arkansas-property-tax-appeal-guide-2026",
  "arkansas-homestead-tax-credit-vs-property-tax-appeal-2026",
  "arkansas-first-time-property-tax-appeal-guide-2026",
  "little-rock-neighborhoods-property-tax-appeal-2026",
  "arkansas-investment-property-tax-appeal-2026",
  "arkansas-evidence-checklist-property-tax-appeal-2026",
  "arkansas-new-homeowner-property-tax-guide-2026",
  "arkansas-mass-appraisal-errors-guide-2026",
  "fayetteville-arkansas-property-tax-appeal-2026",
  "bentonville-rogers-arkansas-property-tax-appeal-2026",
  // ── ALABAMA COUNTY GUIDES (7) ──
  "jefferson-county-alabama-property-tax-appeal-2026",
  "madison-county-alabama-property-tax-appeal-2026",
  "shelby-county-alabama-property-tax-appeal-2026",
  "mobile-county-alabama-property-tax-appeal-2026",
  "montgomery-county-alabama-property-tax-appeal-2026",
  "tuscaloosa-county-alabama-property-tax-appeal-2026",
  "lee-county-alabama-property-tax-appeal-2026",
  // ── ALABAMA EDUCATION / STRATEGY (7) ──
  "alabama-property-tax-appeal-complete-guide-2026",
  "alabama-property-tax-appeal-deadline-2026",
  "alabama-two-way-review-risk-property-tax-appeal",
  "alabama-property-tax-appeal-evidence-checklist-2026",
  "alabama-homestead-exemption-property-tax-guide-2026",
  "alabama-first-time-property-tax-appeal-guide-2026",
  // ── ALABAMA CITY GUIDES (2) ──
  "birmingham-al-property-tax-appeal-2026",
  "huntsville-al-property-tax-appeal-2026",
];

export default function handler(req, res) {
  const base = "https://www.taxappealusa.com";
  const today = new Date().toISOString().split("T")[0];

  const staticPages = [
    { url: "/", priority: "1.0", changefreq: "weekly" },
    { url: "/apply", priority: "0.95", changefreq: "weekly" },
    { url: "/texas", priority: "0.9", changefreq: "monthly" },
    { url: "/georgia", priority: "0.9", changefreq: "monthly" },
    { url: "/florida", priority: "0.9", changefreq: "monthly" },
    { url: "/arkansas", priority: "0.9", changefreq: "monthly" },
    { url: "/alabama", priority: "0.9", changefreq: "monthly" },
    // ── CITY PAGES ──
    { url: "/savannah", priority: "0.8", changefreq: "monthly" },
    { url: "/augusta", priority: "0.8", changefreq: "monthly" },
    { url: "/birmingham", priority: "0.8", changefreq: "monthly" },
    { url: "/huntsville", priority: "0.8", changefreq: "monthly" },
    { url: "/mobile", priority: "0.8", changefreq: "monthly" },
    { url: "/montgomery", priority: "0.8", changefreq: "monthly" },
    { url: "/tuscaloosa", priority: "0.8", changefreq: "monthly" },
    { url: "/montgomery", priority: "0.8", changefreq: "monthly" },
    { url: "/tuscaloosa", priority: "0.8", changefreq: "monthly" },
    { url: "/orlando", priority: "0.8", changefreq: "monthly" },
    { url: "/jacksonville", priority: "0.8", changefreq: "monthly" },
    { url: "/fort-lauderdale", priority: "0.8", changefreq: "monthly" },
    { url: "/houston", priority: "0.85", changefreq: "monthly" },
    { url: "/dallas", priority: "0.85", changefreq: "monthly" },
    { url: "/fort-worth", priority: "0.85", changefreq: "monthly" },
    { url: "/austin", priority: "0.85", changefreq: "monthly" },
    { url: "/san-antonio", priority: "0.85", changefreq: "monthly" },
    { url: "/el-paso", priority: "0.85", changefreq: "monthly" },
    { url: "/atlanta", priority: "0.85", changefreq: "monthly" },
    { url: "/miami", priority: "0.85", changefreq: "monthly" },
    { url: "/tampa", priority: "0.85", changefreq: "monthly" },
    { url: "/bentonville", priority: "0.85", changefreq: "monthly" },
    { url: "/little-rock", priority: "0.85", changefreq: "monthly" },
    { url: "/fayetteville", priority: "0.85", changefreq: "monthly" },
    { url: "/fort-smith", priority: "0.85", changefreq: "monthly" },
    { url: "/partners", priority: "0.7", changefreq: "monthly" },
    { url: "/blog", priority: "0.7", changefreq: "weekly" },
    { url: "/terms", priority: "0.3", changefreq: "yearly" },
    { url: "/privacy", priority: "0.3", changefreq: "yearly" },
  ];

  const countyPages = allCountySlugs.map((s) => ({
    url: `/counties/${s}`,
    priority: "0.8",
    changefreq: "monthly",
  }));

  const floridaNeighborhoodPages = floridaCitySlugs.map((s) => ({
    url: `/florida/${s}`,
    priority: "0.85",
    changefreq: "monthly",
  }));

  const blogPages = blogSlugs.map((s) => ({
    url: `/blog/${s}`,
    priority: "0.75",
    changefreq: "monthly",
  }));

  const allPages = [...staticPages, ...countyPages, ...floridaNeighborhoodPages, ...blogPages];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${allPages
  .map(
    (page) => `  <url>
    <loc>${base}${page.url}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`
  )
  .join("\n")}
</urlset>`;

  res.setHeader("Content-Type", "application/xml");
  res.setHeader("Cache-Control", "public, s-maxage=86400, stale-while-revalidate");
  res.status(200).send(xml);
}
