/**
 * ============================================================================
 * WHICH TEXAS DISTRICTS WE ACTUALLY HOLD A ROLL FOR
 * ============================================================================
 *
 * Risk A in Lookup_Defect_Catalogue_For_Texas_2026-08-26.md, and the single
 * biggest structural difference from Florida.
 *
 * Florida has ONE Department of Revenue roll covering all 67 counties under one
 * schema, so "loaded" is the natural resting state and a coverage gap was
 * theoretical. Texas has 254 appraisal districts publishing separately in at
 * least seven formats. **Partial coverage is the default state here, and will be
 * for a long time.** As of the first El Paso load we hold six districts out of
 * 254 — 2.4% of the state.
 *
 * That inverts the risk. In Florida, a county missing from the roll was a bug.
 * In Texas it is the norm, and the failure mode is specific and severe:
 *
 *   a district we do not hold, reaching the matcher, returns zero rows, and the
 *   homeowner is told "we have no record of your property on the current tax
 *   roll" — about a house that certainly exists, on a roll we simply never
 *   downloaded.
 *
 * That is the same sentence Florida spent four weeks and an unknown number of
 * customers learning not to say. It must say **"we do not cover your county
 * yet"**, in those words, and it must be decided BEFORE any query runs.
 *
 * ============================================================================
 * DERIVED, NEVER HAND-MAINTAINED
 * ============================================================================
 * lib/dor/coverage.js says it in its own header: "keep it generated from the
 * database rather than edited by hand — a county listed here that is not
 * actually loaded turns a coverage gap into 'we have no record of your
 * property', which is the exact wrong answer."
 *
 * So this file lists nothing. It reads lib/tx/countyStats.json, which
 * scripts/tx/county-stats.mjs generates by querying tx_parcels directly. A
 * district appears here if and only if it has rows in the database.
 *
 * The failure this prevents is the AR/AL one recorded in
 * AR_AL_Pages_Sold_A_Refused_State_2026-08-25.md: a fact the code knew, restated
 * by hand somewhere the code could not check, and eleven marketing pages selling
 * two states the funnel refused on sight.
 *
 * AFTER EVERY LOAD, RE-RUN:  node scripts/tx/county-stats.mjs
 * Otherwise this file is stale in the dangerous direction — a freshly loaded
 * county still turned away. `COVERAGE_AS_OF` is exported so callers can surface
 * that rather than guess.
 */

// The .js twin, not the .json — see the note in scripts/tx/county-stats.mjs.
// Both are generated by that script from a live query against tx_parcels.
import stats from './countyStats';
import { CODE_TO_COUNTY } from './counties';

/** When county-stats.mjs last read the database. */
export const COVERAGE_AS_OF = stats.generatedAt || null;

/**
 * { cad_id (number) -> county name }, for every district with rows in
 * tx_parcels. Keys in countyStats.json are strings; callers compare numbers.
 */
export const LOADED_CADS = Object.freeze(
  Object.fromEntries(
    Object.keys(stats.counties || {})
      .map((k) => [Number(k), CODE_TO_COUNTY[Number(k)] || null])
      // A cad_id with no name means counties.js and the database disagree about
      // which districts exist. Surfacing null would put "undefined County" in
      // front of a customer, so it is dropped here and reported by
      // UNNAMED_CADS below rather than rendered.
      .filter(([, name]) => name),
  ),
);

/** cad_ids present in the database that counties.js cannot name. Expected: []. */
export const UNNAMED_CADS = Object.freeze(
  Object.keys(stats.counties || {})
    .map(Number)
    .filter((c) => !CODE_TO_COUNTY[c]),
);

export const LOADED_CAD_IDS = Object.freeze(Object.keys(LOADED_CADS).map(Number).sort((a, b) => a - b));
export const LOADED_COUNTY_NAMES = Object.freeze(Object.values(LOADED_CADS).sort());

/** True when we hold a roll for this district and the matcher may run. */
export function isCovered(cadId) {
  return Object.prototype.hasOwnProperty.call(LOADED_CADS, Number(cadId));
}

/**
 * Resolve a county NAME to a cad_id we actually hold, or null.
 *
 * Deliberately does not fall back to countyCode() for an uncovered county: the
 * whole point is that an uncovered district must not acquire a cad_id and slip
 * into a query. Callers that need the code regardless import counties.js.
 */
export function coveredCadFromName(name) {
  if (!name) return null;
  const want = String(name).replace(/\s+county$/i, '').trim().toLowerCase();
  const hit = Object.entries(LOADED_CADS).find(([, n]) => n.toLowerCase() === want);
  return hit ? Number(hit[0]) : null;
}

/**
 * Texas ZIP prefixes: 75–79 plus 885 (El Paso's far-west block).
 *
 * A HINT, NOT A GATE — defect 4. ZIP narrows and never excludes: a homeowner
 * whose USPS ZIP differs from the district's recorded one is common and is not
 * their mistake. This exists to spot an obviously-not-Texas address before we
 * bother the database, not to decide that a Texas address is invalid.
 */
export function isTexasZip(zip) {
  const z = String(zip || '').trim().slice(0, 5);
  if (!/^\d{5}$/.test(z)) return false;
  return /^7[5-9]/.test(z) || z.startsWith('885');
}

export default {
  COVERAGE_AS_OF, LOADED_CADS, LOADED_CAD_IDS, LOADED_COUNTY_NAMES,
  UNNAMED_CADS, isCovered, coveredCadFromName, isTexasZip,
};
