// GENERATED by scripts/tx/hearing-outcomes.mjs — do not edit.
// Outcome figures published on county pages. Re-run after each roll refresh.
export default {
  "_comment": "Generated by scripts/tx/hearing-outcomes.mjs. Do not hand-edit — rerun the script.",
  "generatedAt": "2026-09-10",
  "districts": {
    "101": {
      "taxYear": 2026,
      "stateClass": "A1",
      "accounts": 1157703,
      "filed": 424251,
      "filedPctOfClass": 36.6,
      "withHearingRecord": 393222,
      "filedWithNoHearingRecord": 31029,
      "reduced": 335537,
      "reducedPctOfFiled": 79.1,
      "medianReduction": 22839,
      "medianReductionPctOfValue": 6.41,
      "meanReduction": 48046,
      "ownerFiled": {
        "heard": 69054,
        "reduced": 58911,
        "reducedPct": 85.3
      },
      "agentFiled": {
        "heard": 324168,
        "reduced": 276626,
        "reducedPct": 85.3
      },
      "source": "Harris Central Appraisal District, arb_hearings_real.txt (Hearing_files.zip)",
      "sourceBuiltOn": "2026-09-06",
      "basis": "Denominator is every account of this class with protested=Y on the roll. Accounts that filed and have no hearing record count as NO reduction. Numerator is accounts whose largest recorded hearing outcome lowered the appraised value.",
      "computedAt": "2026-09-10"
    }
  }
};
