/**
 * Arkansas City / Suburb Data — lib/arkansasSuburbs.js
 * 20 key cities across the state's top markets.
 *
 * Arkansas residential assessment ratio: 20% of fair market value
 * Appeal deadline: Third Monday in August (Aug 17, 2026)
 * Appeal body: County Board of Equalization (BOE)
 * Governing statute: Ark. Code §26-27-317 (appeal rights), §26-26-1901 (market value)
 * Amendment 79: homestead assessment increase capped at 5%/yr; frozen for 65+ owners
 */

const AR_SUBURBS = [
  // ── NORTHWEST ARKANSAS (NWA) ──────────────────────────────────────────────
  {
    slug: "bentonville-ar",
    name: "Bentonville",
    county: "Benton",
    countySlug: "benton-county-ar",
    district: "Benton County Assessor",
    districtUrl: "https://www.bentoncountyar.gov/assessor",
    metro: "Northwest Arkansas",
    medianValue: 420000,
    avgSavings: 680,
    pop: "high",
    description: "Bentonville is the global headquarters of Walmart and one of the fastest-growing cities in the South, drawing tech workers, corporate relocations, and international visitors to its world-class cycling trails and Crystal Bridges Museum. Rapid home price appreciation in Bentonville's newer master-planned communities frequently outpaces the Benton County Assessor's mass-appraisal models, creating consistent over-assessment opportunities.",
  },
  {
    slug: "rogers-ar",
    name: "Rogers",
    county: "Benton",
    countySlug: "benton-county-ar",
    district: "Benton County Assessor",
    districtUrl: "https://www.bentoncountyar.gov/assessor",
    metro: "Northwest Arkansas",
    medianValue: 380000,
    avgSavings: 610,
    pop: "high",
    description: "Rogers anchors the western corridor of Northwest Arkansas with its Pinnacle Hills retail district, Railyard arts scene, and growing base of tech and logistics employers. The city's wide mix of housing types — from 1960s ranch homes to $700,000 new construction — creates wide valuation variance that Benton County's broad assessment models routinely miss.",
  },
  {
    slug: "fayetteville-ar",
    name: "Fayetteville",
    county: "Washington",
    countySlug: "washington-county-ar",
    district: "Washington County Assessor",
    districtUrl: "https://www.co.washington.ar.us/assessor",
    metro: "Northwest Arkansas",
    medianValue: 320000,
    avgSavings: 520,
    pop: "high",
    description: "Fayetteville is home to the University of Arkansas and serves as the cultural and economic heart of the Ozarks. Rapid student-driven demand and a booming tech corridor on south Fayetteville's Steele Boulevard have pushed home values up sharply — while Washington County Assessor appraisals often rely on older comparable sales that understate current market corrections.",
  },
  {
    slug: "springdale-ar",
    name: "Springdale",
    county: "Washington",
    countySlug: "washington-county-ar",
    district: "Washington County Assessor",
    districtUrl: "https://www.co.washington.ar.us/assessor",
    metro: "Northwest Arkansas",
    medianValue: 260000,
    avgSavings: 420,
    pop: "high",
    description: "Springdale is the manufacturing and logistics hub of Northwest Arkansas, home to Tyson Foods' global headquarters and a large and fast-growing international community. Washington County's mass-appraisal models frequently struggle with Springdale's diverse housing stock — from older worker housing near downtown to newer subdivisions along the Highway 412 corridor.",
  },
  {
    slug: "siloam-springs-ar",
    name: "Siloam Springs",
    county: "Benton",
    countySlug: "benton-county-ar",
    district: "Benton County Assessor",
    districtUrl: "https://www.bentoncountyar.gov/assessor",
    metro: "Northwest Arkansas",
    medianValue: 230000,
    avgSavings: 370,
    pop: "medium",
    description: "Siloam Springs sits near the Oklahoma border with a growing John Brown University population and a charming historic downtown. Benton County's county-wide assessment models often apply NWA metro-level appreciation assumptions to Siloam Springs, leading to over-assessed values on smaller lots and older homes in the city's established neighborhoods.",
  },
  // ── CENTRAL ARKANSAS (LITTLE ROCK METRO) ─────────────────────────────────
  {
    slug: "little-rock-ar",
    name: "Little Rock",
    county: "Pulaski",
    countySlug: "pulaski-county-ar",
    district: "Pulaski County Assessor",
    districtUrl: "https://www.pulaskicountyassessor.net",
    metro: "Little Rock",
    medianValue: 220000,
    avgSavings: 360,
    pop: "high",
    description: "Little Rock is Arkansas's capital and largest city, with a diverse housing market spanning historic Heights homes, River Market condos, and suburban West Little Rock estates. With tens of thousands of parcels to value, the Pulaski County Assessor's mass-appraisal process is especially prone to error in Little Rock's highly varied neighborhoods.",
  },
  {
    slug: "north-little-rock-ar",
    name: "North Little Rock",
    county: "Pulaski",
    countySlug: "pulaski-county-ar",
    district: "Pulaski County Assessor",
    districtUrl: "https://www.pulaskicountyassessor.net",
    metro: "Little Rock",
    medianValue: 200000,
    avgSavings: 320,
    pop: "high",
    description: "North Little Rock sits across the Arkansas River from the capital with its own distinct neighborhoods, from the Argenta Arts District to suburban Lakeshore. Pulaski County assessors evaluate thousands of parcels using statistical models that frequently over-value North Little Rock's highly varied post-World War II housing stock.",
  },
  {
    slug: "maumelle-ar",
    name: "Maumelle",
    county: "Pulaski",
    countySlug: "pulaski-county-ar",
    district: "Pulaski County Assessor",
    districtUrl: "https://www.pulaskicountyassessor.net",
    metro: "Little Rock",
    medianValue: 270000,
    avgSavings: 440,
    pop: "medium",
    description: "Maumelle is a planned community on the Arkansas River northwest of Little Rock, popular with young families and professionals who want suburban space within commuting distance of the capital. Its well-maintained planned neighborhoods and newer construction create assessment challenges that Pulaski County's models frequently handle imprecisely.",
  },
  {
    slug: "sherwood-ar",
    name: "Sherwood",
    county: "Pulaski",
    countySlug: "pulaski-county-ar",
    district: "Pulaski County Assessor",
    districtUrl: "https://www.pulaskicountyassessor.net",
    metro: "Little Rock",
    medianValue: 230000,
    avgSavings: 370,
    pop: "medium",
    description: "Sherwood is northeast Pulaski County's most established suburb, known for its military ties to Little Rock Air Force Base and its stable residential neighborhoods. Pulaski County's county-wide assessment models often apply market-wide trends that don't account for Sherwood's specific neighborhood-level conditions and lot variations.",
  },
  {
    slug: "conway-ar",
    name: "Conway",
    county: "Faulkner",
    countySlug: "faulkner-county-ar",
    district: "Faulkner County Assessor",
    districtUrl: "https://www.faulknercounty.org/government/elected-offices/assessor",
    metro: "Little Rock",
    medianValue: 260000,
    avgSavings: 420,
    pop: "high",
    description: "Conway is one of Arkansas's fastest-growing cities, anchored by three major universities — University of Central Arkansas, Hendrix College, and Central Baptist College. The resulting student housing demand and rapid new construction have pushed assessed values in Conway's established neighborhoods to levels that don't reflect actual market conditions.",
  },
  {
    slug: "benton-ar",
    name: "Benton",
    county: "Saline",
    countySlug: "saline-county-ar",
    district: "Saline County Assessor",
    districtUrl: "https://www.salinecountyar.gov/assessor",
    metro: "Little Rock",
    medianValue: 240000,
    avgSavings: 390,
    pop: "medium",
    description: "Benton is Saline County's seat and a growing Little Rock bedroom community, popular with commuters seeking larger lots and quieter neighborhoods than the capital offers. Saline County's assessments frequently lag behind actual market softening in Benton's newer subdivisions along the I-30 and Highway 5 corridors.",
  },
  {
    slug: "bryant-ar",
    name: "Bryant",
    county: "Saline",
    countySlug: "saline-county-ar",
    district: "Saline County Assessor",
    districtUrl: "https://www.salinecountyar.gov/assessor",
    metro: "Little Rock",
    medianValue: 255000,
    avgSavings: 410,
    pop: "medium",
    description: "Bryant has consistently ranked as one of America's fastest-growing cities, driven by its top-rated schools and affordable commute to Little Rock. Rapid new construction and shifting resale prices create valuation gaps that Saline County's mass-appraisal process regularly misses in Bryant's active development corridors.",
  },
  // ── FORT SMITH METRO ──────────────────────────────────────────────────────
  {
    slug: "fort-smith-ar",
    name: "Fort Smith",
    county: "Sebastian",
    countySlug: "sebastian-county-ar",
    district: "Sebastian County Assessor",
    districtUrl: "https://www.sebastiancountyar.gov/assessor",
    metro: "Fort Smith",
    medianValue: 180000,
    avgSavings: 290,
    pop: "high",
    description: "Fort Smith is Arkansas's second-largest city and the gateway to the Arkansas River Valley, with a diverse economy anchored by manufacturing, healthcare, and cross-border commerce with Oklahoma. Sebastian County's mass-appraisal models handle Fort Smith's large and varied housing inventory with statistical averages that often produce inflated assessments in established older neighborhoods.",
  },
  {
    slug: "van-buren-ar",
    name: "Van Buren",
    county: "Crawford",
    countySlug: "crawford-county-ar",
    district: "Crawford County Assessor",
    districtUrl: "https://crawfordcountyar.gov/assessor",
    metro: "Fort Smith",
    medianValue: 175000,
    avgSavings: 280,
    pop: "medium",
    description: "Van Buren anchors Crawford County across the Arkansas River from Fort Smith, with a charming historic Main Street and a mix of older bungalows and newer suburban growth. Crawford County's assessment process relies on broad market trends that don't always capture the specific condition and location factors that drive value differences within Van Buren.",
  },
  // ── NORTHEAST ARKANSAS ────────────────────────────────────────────────────
  {
    slug: "jonesboro-ar",
    name: "Jonesboro",
    county: "Craighead",
    countySlug: "craighead-county-ar",
    district: "Craighead County Assessor",
    districtUrl: "https://www.craigheadcounty.org/assessor",
    metro: "Jonesboro",
    medianValue: 220000,
    avgSavings: 355,
    pop: "high",
    description: "Jonesboro is Arkansas State University's home and the economic hub of the Arkansas Delta, with a growing healthcare sector and manufacturing base. Craighead County's assessment models use broad market data that frequently produces inconsistent results across Jonesboro's wide range of housing types, from historic neighborhoods near ASU to newer subdivisions along the Highway 63 bypass.",
  },
  {
    slug: "paragould-ar",
    name: "Paragould",
    county: "Greene",
    countySlug: "greene-county-ar",
    district: "Greene County Assessor",
    districtUrl: "https://www.greenecountyar.gov/assessor",
    metro: "Jonesboro",
    medianValue: 160000,
    avgSavings: 258,
    pop: "medium",
    description: "Paragould is Greene County's seat and Northeast Arkansas's second-largest city, with a manufacturing and agriculture-based economy. Greene County's assessments for Paragould's newer subdivisions near the I-555 corridor often apply broad market data that misses localized market conditions and neighborhood-level variations.",
  },
  // ── CENTRAL / GARLAND COUNTY ──────────────────────────────────────────────
  {
    slug: "hot-springs-ar",
    name: "Hot Springs",
    county: "Garland",
    countySlug: "garland-county-ar",
    district: "Garland County Assessor",
    districtUrl: "https://www.garlandcounty.org/assessor",
    metro: "Hot Springs",
    medianValue: 250000,
    avgSavings: 404,
    pop: "high",
    description: "Hot Springs is Arkansas's premier resort city, with lakefront properties on Lake Hamilton and Lake Catherine alongside the historic Bathhouse Row National Park. Garland County's mass-appraisal models frequently struggle to accurately value Hot Springs' unique mix of lakefront estates, resort condos, and historic Victorian-era homes in Quapaw Quarter.",
  },
  // ── WHITE RIVER / OZARKS ──────────────────────────────────────────────────
  {
    slug: "searcy-ar",
    name: "Searcy",
    county: "White",
    countySlug: "white-county-ar",
    district: "White County Assessor",
    districtUrl: "https://www.whitecountyar.gov/assessor",
    metro: "Little Rock",
    medianValue: 195000,
    avgSavings: 315,
    pop: "medium",
    description: "Searcy is White County's seat and home to Harding University, with a stable, education-driven economy and a wide mix of housing from established neighborhoods near the college to newer subdivisions on the city's growing eastern edge. White County's assessment models often apply metro-area appreciation rates that don't reflect Searcy's more measured market conditions.",
  },
  // ── SOUTH ARKANSAS ────────────────────────────────────────────────────────
  {
    slug: "pine-bluff-ar",
    name: "Pine Bluff",
    county: "Jefferson",
    countySlug: "jefferson-county-ar",
    district: "Jefferson County Assessor",
    districtUrl: "https://www.jeffersoncountyar.gov/assessor",
    metro: "Pine Bluff",
    medianValue: 130000,
    avgSavings: 210,
    pop: "medium",
    description: "Pine Bluff is Jefferson County's seat and one of Arkansas's major industrial and agricultural centers on the Arkansas River. Jefferson County's assessments cover a wide range of property types, and mass-appraisal models frequently produce valuations on Pine Bluff's established older neighborhoods that don't reflect actual market transaction prices.",
  },
  {
    slug: "texarkana-ar",
    name: "Texarkana",
    county: "Miller",
    countySlug: "miller-county-ar",
    district: "Miller County Assessor",
    districtUrl: "https://www.millercountyar.gov/assessor",
    metro: "Texarkana",
    medianValue: 195000,
    avgSavings: 315,
    pop: "medium",
    description: "Texarkana straddles the Arkansas-Texas state line, creating a unique dual-market dynamic where Miller County (AR) homeowners on the Arkansas side file appeals separately from their Texas-side neighbors. Miller County's assessments are particularly prone to error due to the complexity of pricing homes in a border market where buyers actively compare across both states.",
  },
];

/**
 * Get all static paths for Next.js getStaticPaths
 */
export function getAllArSuburbSlugs() {
  return AR_SUBURBS.map((c) => ({ params: { city: c.slug } }));
}

/**
 * Look up a city by slug
 */
export function getArSuburbBySlug(slug) {
  return AR_SUBURBS.find((c) => c.slug === slug) || null;
}

export default AR_SUBURBS;
