/**
 * Florida Value Adjustment Board (VAB) Clerk mailing addresses — all 67 counties.
 *
 * WHY THIS FILE EXISTS:
 * A DR-486 petition and its filing-fee check must be mailed to the CLERK OF THE
 * VALUE ADJUSTMENT BOARD — *not* to the county Property Appraiser. Mailing to the
 * Property Appraiser means the petition is never filed and the customer loses the
 * appeal year. Before this file existed, the destination address was generated by
 * an LLM at request time and cached in Redis for 180 days, unvalidated. That is
 * never acceptable for addressing government mail. This table is the single source
 * of truth and the filing path must not fall back to any other source.
 *
 * DO NOT GUESS. If a county is not `confirmed` below, orders for that county are
 * blocked at checkout (see isFlCountySupported). A blocked sale is recoverable;
 * a misdelivered petition is not.
 *
 * NOTE — non-obvious VAB clerks (these are NOT the Clerk of the Circuit Court):
 *   Orange   → Orange County Comptroller
 *   Duval    → City of Jacksonville, City Hall
 *   Broward  → County VAB office, Governmental Center Room 120
 *   Volusia  → County Council administration building
 *   Pasco    → Board Records Division
 *   Pinellas → Board Records Department
 *
 * Researched 2026-07-28 from official county government sources. Each entry
 * carries the sourceUrl it was verified against.
 *
 * REVIEW REMINDER: the 12 `unconfirmed` counties each need one phone call to the
 * VAB clerk to confirm the petition mailing address. Until then they are blocked.
 */

// Counties that require PHYSICAL RECEIPT by the deadline and explicitly state
// that a postmark is NOT sufficient. These need extra lead time before the
// deadline — see lib/filingWindows.js.
export const FL_POSTMARK_NOT_ACCEPTED = ['Pasco', 'Marion'];

const FL_VAB_ADDRESSES = {
  "Alachua": { vabName: "Alachua County Clerk of Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "12 SE 1st Street, 4th Floor", city: "Gainesville", state: "FL", zip: "32601", confidence: "confirmed", sourceUrl: "https://alachuacounty.us/depts/clerk/vab/pages/valueadjustmentboard.aspx" },
  "Baker": { vabName: "Baker County Clerk of the Circuit Court – Clerk to the VAB", attn: "Attn: VAB", street: "339 E Macclenny Avenue", city: "Macclenny", state: "FL", zip: "32063", confidence: "confirmed", sourceUrl: "https://bakerclerk.com/vab/" },
  "Bay": { vabName: "Bay County Clerk of Court & Comptroller – Clerk of the Value Adjustment Board", attn: "Attn: Clerk of the Value Adjustment Board", street: "225 McKenzie Avenue", city: "Panama City", state: "FL", zip: "32401", confidence: "confirmed", sourceUrl: "https://www.baycoclerk.com/clerk-services/value-adjustment-board/" },
  // OPENED 13 Aug 2026 FROM PUBLISHED SOURCES, no phone call needed. The Clerk's own
  // "When and how to file your VAB petition" page gives the mailing address, and its
  // companion fees page gives both the fee and — the part we had wrong — the payee:
  //   "P.O. Drawer B Starke, FL 32091"
  //   "checks (made payable to the Clerk of Court)"
  // We held "Board of County Commissioners". Same defect as Nassau, found the same week:
  // a guessed payee that happens to be the common Florida answer and is wrong here.
  // See lib/flCountyFees.js for the payee correction.
  "Bradford": { vabName: "Bradford County Clerk of the Circuit Court & Comptroller – Clerk to the VAB", attn: "Attn: Value Adjustment Board", street: "P.O. Drawer B", city: "Starke", state: "FL", zip: "32091", confidence: "confirmed", sourceUrl: "https://bradfordclerk.com/value-adjustment-board/when-and-how-to-file-your-vab-petition/", note: "CONFIRMED 13 Aug 2026 from the Clerk's own VAB filing page, which publishes the address verbatim. Fees page also publishes the $50 fee and the payee. No filing fee is charged for an appeal against denial of homestead exemption or homestead tax deferral — we do not file those." },
  "Brevard": { vabName: "Brevard County Clerk of Courts – Value Adjustment Board", attn: "Value Adjustment Board", street: "P.O. Box 999", city: "Titusville", state: "FL", zip: "32781-0999", confidence: "confirmed", sourceUrl: "http://www.brevardclerk.us/file-a-petition" },
  "Broward": { vabName: "Broward County Value Adjustment Board", attn: "Value Adjustment Board", street: "115 S. Andrews Avenue, Room 120", city: "Fort Lauderdale", state: "FL", zip: "33301", confidence: "confirmed", sourceUrl: "https://www.broward.org/VAB/Pages/FilingAPetition.aspx" },
  "Calhoun": { vabName: "Calhoun County Clerk of Circuit Court – Clerk to the Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "20859 Central Ave. East, Room 130", city: "Blountstown", state: "FL", zip: "32424", confidence: "confirmed", sourceUrl: "https://calhounclerk.com/clerk-to-the-board/value-adjustment-board/" },
  "Charlotte": { vabName: "Charlotte County Value Adjustment Board", attn: "Value Adjustment Board", street: "18500 Murdock Circle, Room 416", city: "Port Charlotte", state: "FL", zip: "33948", confidence: "confirmed", sourceUrl: "https://charlotteclerk.com/departments/vab/" },
  "Citrus": { vabName: "Citrus County Clerk of Courts – Value Adjustment Board", attn: "Attn: VAB", street: "110 N Apopka Avenue", city: "Inverness", state: "FL", zip: "34450", confidence: "confirmed", sourceUrl: "https://citrusclerk.org/216/Value-Adjustment-Board" },
  "Clay": { vabName: "Clay County Clerk of Court & Comptroller – Clerk to the Value Adjustment Board", attn: "Attn: Clerk to the Value Adjustment Board", street: "P.O. Box 698", city: "Green Cove Springs", state: "FL", zip: "32043", confidence: "confirmed", sourceUrl: "https://clayclerk.com/departments/value-adjustment-board/petitions-appeals-forms/" },
  "Collier": { vabName: "Collier County Clerk of the Circuit Court – Board Minutes & Records (VAB)", attn: "Attn: Value Adjustment Board", street: "3299 Tamiami Trail East, Suite 401", city: "Naples", state: "FL", zip: "34112-5746", confidence: "confirmed", sourceUrl: "https://www.collierclerk.com/board-records-vab/value-adjustment-board/" },
  // ROOM 225 -> ROOM 214, corrected by phone 13 Aug 2026 (Nathan). The 225 came from the
  // Clerk's published VAB page and had been marked `confirmed` since it was loaded, which
  // is the point: `confirmed` records that a source was read once, not that it is right
  // today. Same shape as DeSoto on 6 Aug, where the held address was wrong by building
  // number AND suite. A wrong room inside the right building is the worst version of this
  // — the envelope reaches the courthouse and stops there, and Florida is receipt-based.
  "Columbia": { vabName: "Columbia County Clerk of the Circuit Court & Comptroller – Clerk to VAB", attn: "Attn: Clerk to the Value Adjustment Board", street: "173 NE Hernando Avenue, Room 214", city: "Lake City", state: "FL", zip: "32055", confidence: "confirmed", sourceUrl: "https://columbiaclerk.com/value-adjustment-board/", note: "CONFIRMED BY PHONE 13 Aug 2026 (Nathan). Room corrected 225 -> 214; the Clerk's own VAB page still publishes 225. Phone answer taken as authoritative over the website, same call as Sarasota 6 Aug." },
  "DeSoto": { vabName: "DeSoto County Clerk of the Circuit Court – Clerk to the VAB", attn: "Attn: Value Adjustment Board", street: "201 E Oak St #201", city: "Arcadia", state: "FL", zip: "34266", confidence: "confirmed", sourceUrl: "https://www.desotoclerk.com/contact/", note: "CONFIRMED BY PHONE 2026-08-06 (Nathan). Address corrected from 115 East Oak Street Room 101 to 201 E Oak St #201 — a different building number AND suite, so the previous value would have misdelivered. Fee also corrected 15 -> 50; see lib/flCountyFees.js." },
  "Dixie": { vabName: "Dixie County Clerk of Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 1206", city: "Cross City", state: "FL", zip: "32628", confidence: "unconfirmed", sourceUrl: "https://dixieclerk.com/value-adjustment-board-forms", note: "No dedicated petition mailing address published. Confirm by phone." },
  "Duval": { vabName: "Clerk of the Value Adjustment Board – City of Jacksonville", attn: "Clerk of the Value Adjustment Board", street: "117 West Duval Street, Suite 305", city: "Jacksonville", state: "FL", zip: "32202", confidence: "confirmed", sourceUrl: "https://www.jacksonville.gov/departments/boards-and-commissions/value-adjustment-board" },
  "Escambia": { vabName: "Escambia County Clerk of the Circuit Court and Comptroller – Clerk to the VAB", attn: "Attn: Clerk to the Value Adjustment Board", street: "221 Palafox Place, Suite 110", city: "Pensacola", state: "FL", zip: "32502-5843", confidence: "confirmed", sourceUrl: "https://www.escambiaclerk.com/264/Value-Adjustment-Board-VAB-Information-a" },
  "Flagler": { vabName: "Flagler County Clerk & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "1769 E Moody Blvd, Bldg 1", city: "Bunnell", state: "FL", zip: "32110", confidence: "confirmed", sourceUrl: "https://flaglerclerk.gov/vab/" },
  "Franklin": { vabName: "Franklin County Clerk of the Circuit Court & Comptroller", attn: "Attn: Value Adjustment Board", street: "33 Market Street, Suite 203", city: "Apalachicola", state: "FL", zip: "32320", confidence: "unconfirmed", sourceUrl: "https://www.franklinclerk.com/clerk-services/bocc-records/", note: "No dedicated petition mailing address published. Confirm by phone." },
  "Gadsden": { vabName: "Gadsden County Clerk of the Circuit Court", attn: "Attn: Value Adjustment Board", street: "P.O. Box 1649", city: "Quincy", state: "FL", zip: "32353-1649", confidence: "unconfirmed", sourceUrl: "https://www.fl-counties.com/directory-results/?county=Gadsden%20County", note: "Not verified on an official VAB page. Physical: 10 E Jefferson St, Quincy, FL 32351. Confirm by phone." },
  "Gilchrist": { vabName: "Gilchrist County Clerk of the Circuit Court & Comptroller – Clerk to the VAB", attn: "Attn: Value Adjustment Board", street: "P.O. Box 37", city: "Trenton", state: "FL", zip: "32693", confidence: "unconfirmed", sourceUrl: "https://gilchristclerk.com/value-adjustment-board/", note: "No dedicated petition mailing address published. Physical: 112 S. Main St. Confirm by phone." },
  "Glades": { vabName: "Glades County Clerk of the Circuit Court & Comptroller – Clerk to the VAB", attn: "Attn: Clerk to the Value Adjustment Board", street: "500 Avenue J, Suite 102", city: "Moore Haven", state: "FL", zip: "33471", confidence: "confirmed", sourceUrl: "https://gladesclerk.com/clerk-services/value-adjustment-board/" },
  "Gulf": { vabName: "Gulf County Clerk of the Circuit Court – VAB Clerk", attn: "Attn: VAB Clerk", street: "1000 Cecil G. Costin, Sr. Blvd., Room 149", city: "Port St. Joe", state: "FL", zip: "32456", confidence: "confirmed", sourceUrl: "https://www.gulfclerk.com/value-adjustment-board/" },
  "Hamilton": { vabName: "Hamilton County Clerk of Circuit Court – Clerk of the Value Adjustment Board", attn: "Attn: Clerk of the Value Adjustment Board", street: "207 NE 1st Street, Room 106", city: "Jasper", state: "FL", zip: "32052", confidence: "confirmed", sourceUrl: "https://hamiltonclerk.com/value-adjustment-board/" },
  // OPENED 13 Aug 2026 FROM PUBLISHED SOURCES. The Clerk's VAB department page publishes
  // the address, and its Information subpage publishes the fee with the statute behind it:
  //   "417 West Main Street, Suite 202, Wauchula, FL 33873"
  //   "The filing fee of $50.00, pursuant to Florida Statute 194.013(1) should accompany
  //    the petition"
  // The suite number we held is confirmed exactly.
  //
  // DO NOT CONFUSE WITH THE HEARING ROOM. The same site gives 412 West Orange Street,
  // Room 102 as where the VAB meets. That is not where a petition is mailed.
  //
  // PAYEE IS STILL UNPUBLISHED — we hold "Board of County Commissioners" on no evidence.
  // Bradford and Nassau both turned out to be the Clerk, so treat this as an open question,
  // not a safe default: 863-773-4174 x7295.
  "Hardee": { vabName: "Hardee County Clerk of the Circuit Court and Comptroller – VAB Clerk", attn: "Attn: Value Adjustment Board Clerk", street: "417 West Main Street, Suite 202", city: "Wauchula", state: "FL", zip: "33873", confidence: "confirmed", sourceUrl: "https://www.hardeeclerk.com/departments/value-adjustment-board/", note: "CONFIRMED 13 Aug 2026 from the Clerk's VAB department page. Payee NOT published anywhere — the held 'Board of County Commissioners' is a guess and Bradford/Nassau both proved that guess wrong elsewhere. Their Information subpage still shows the TY2025 deadline (9 Sept 2025); TY2026 not posted as of 13 Aug." },
  "Hendry": { vabName: "Hendry County Clerk of Circuit Court – Value Adjustment Board", attn: "Value Adjustment Board", street: "P.O. Box 1760", city: "LaBelle", state: "FL", zip: "33975", confidence: "confirmed", sourceUrl: "https://www.hendryclerk.org/value-adjustment-board/", note: "Courier/FedEx/UPS: 25 E. Hickpochee Ave., LaBelle, FL 33935" },
  "Hernando": { vabName: "Hernando County Clerk of Circuit Court & Comptroller – Clerk to the VAB", attn: "Clerk to the Value Adjustment Board", street: "20 N. Main Street, Room 362", city: "Brooksville", state: "FL", zip: "34601", confidence: "confirmed", sourceUrl: "https://hernandoclerk.com/county-services/value-adjustment-board/" },
  "Highlands": { vabName: "Highlands County Clerk of Courts – Value Adjustment Board", attn: "Attn: Value Adjustment Clerk", street: "590 S Commerce Avenue", city: "Sebring", state: "FL", zip: "33870", confidence: "confirmed", sourceUrl: "https://www.highlandsclerkfl.gov/clerk_to_the_board/value_adjustment_board/index.php" },
  "Hillsborough": { vabName: "Hillsborough County Clerk of Circuit Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "601 East Kennedy Blvd, Floor 12", city: "Tampa", state: "FL", zip: "33602", confidence: "confirmed", sourceUrl: "https://www.hillsclerk.com/about-us/forms/value-adjustment-board-forms" },
  "Holmes": { vabName: "Holmes County Clerk's Finance Office – Value Adjustment Board", attn: "Attn: VAB", street: "201 N. Oklahoma Street, Suite 205", city: "Bonifay", state: "FL", zip: "32425", confidence: "confirmed", sourceUrl: "https://holmesclerk.com/other-services/value-adjustment-board/" },
  "Indian River": { vabName: "Indian River County Value Adjustment Board – Clerk to the Board", attn: "Attn: Value Adjustment Board", street: "1801 27th Street, A2-801", city: "Vero Beach", state: "FL", zip: "32960", confidence: "confirmed", sourceUrl: "https://vab.indian-river.org/" },
  "Jackson": { vabName: "Jackson County Clerk of the Circuit Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Drawer 510", city: "Marianna", state: "FL", zip: "32447", confidence: "confirmed", sourceUrl: "https://www.jacksonclerk.com/clerk-services/value-adjustment-board/", note: "Physical: 4445 Lafayette Street, Marianna, FL 32446" },
  "Jefferson": { vabName: "Jefferson County Clerk of the Circuit Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "1 Courthouse Circle", city: "Monticello", state: "FL", zip: "32344", confidence: "confirmed", sourceUrl: "https://www.jeffersonclerk.com/clerk-services/value-adjustment-board/" },
  "Lafayette": { vabName: "Lafayette County Clerk of Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 88", city: "Mayo", state: "FL", zip: "32066", confidence: "confirmed", sourceUrl: "https://www.lafayetteclerk.com/departments-services/clerk-services/value-adjustment-board/" },
  "Lake": { vabName: "Lake County Clerk of the Circuit Court & Comptroller – Value Adjustment Board", attn: "Value Adjustment Board", street: "P.O. Box 7800", city: "Tavares", state: "FL", zip: "32778", confidence: "confirmed", sourceUrl: "https://www.lakecountyclerkfl.gov/" },
  "Lee": { vabName: "Lee County Clerk of Court – Value Adjustment Board", attn: "Value Adjustment Board", street: "P.O. Box 2469", city: "Fort Myers", state: "FL", zip: "33902", confidence: "confirmed", sourceUrl: "https://www.leeclerk.org/departments/value-adjustment-board-vab" },
  "Leon": { vabName: "Leon County Clerk of Court – Value Adjustment Board", attn: "Attn: Clerk Finance Department / Value Adjustment Board", street: "301 S. Monroe Street, #100", city: "Tallahassee", state: "FL", zip: "32301", confidence: "confirmed", sourceUrl: "https://cvweb.leonclerk.com/public/clerk_services/administration/value_adjustment_board/vab.asp" },
  "Levy": { vabName: "Levy County Clerk of the Circuit Court – Value Adjustment Board", attn: "Attn: VAB Clerk", street: "355 South Court Street", city: "Bronson", state: "FL", zip: "32621", confidence: "confirmed", sourceUrl: "https://www.levyclerk.com/value-adjustment-board/" },
  "Liberty": { vabName: "Liberty County Clerk of Circuit Court & County Comptroller – Clerk to the VAB", attn: "Attn: Value Adjustment Board", street: "P.O. Box 399", city: "Bristol", state: "FL", zip: "32321", confidence: "confirmed", sourceUrl: "https://libertycountyfl.org/value-adjustment-board/", note: "Physical: 10818 NW SR 20, Bristol, FL 32321" },
  // ==========================================================================
  // MADISON — CALLED AND DELIBERATELY NOT CONFIRMED. DO NOT "FINISH" THIS ONE.
  // ==========================================================================
  // Nathan called 13 Aug 2026. The clerk was unsure of the mailing address, the
  // fee AND the payee, and was hostile about being asked at all. Nothing usable
  // came back, so nothing was entered. Decision the same day: stop spending
  // calls on Madison this season and leave both gates shut.
  //
  // WHY THIS COMMENT EXISTS RATHER THAN JUST LEAVING IT UNCONFIRMED. The entry
  // below looks identical to a county nobody has got round to yet — same
  // `unconfirmed`, same "Confirm by phone" note, same published phone number on
  // the call sheet. Without this, the next person reads it as an open task,
  // makes the same call, gets the same mess, and may well type the answers in.
  // A county that has been tried and failed must not look like one that has not
  // been tried.
  //
  // WHAT WOULD CHANGE IT: written confirmation only — an email from the clerk,
  // or the county's own published VAB resolution / petition instructions naming
  // the address, fee and payee. A phone answer must not flip this gate, because
  // the phone answer is the thing that failed. Florida is receipt-based: a wrong
  // address means the petition never arrives and the owner learns of it after
  // 18 Sept, with no way to refile. Madison is `pop: "low"` in countyData.js;
  // the orders at stake do not come close to paying for that outcome once.
  //
  // Precedent for the risk, both from entries already marked confirmed: DeSoto's
  // address was wrong by building number AND suite (6 Aug), and Duval/Seminole
  // held $15 against a real $50 (30 Jul), which is a rejected petition.
  "Madison": { vabName: "Madison County Clerk of Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 237", city: "Madison", state: "FL", zip: "32341", confidence: "unconfirmed", sourceUrl: "https://www.madisonclerk.com/departments-services/departments/value-adjustment-board/", note: "CALLED 13 Aug 2026 (Nathan) — clerk unsure of address, fee and payee, and unwilling. Nothing entered. Do NOT promote to confirmed on a phone answer; written confirmation only. No dedicated petition mailing address published. Physical: 125 SW Range Ave." },
  "Manatee": { vabName: "Manatee County Clerk of the Circuit Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 25400", city: "Bradenton", state: "FL", zip: "34206", confidence: "confirmed", sourceUrl: "https://www.manateeclerk.com/departments/value-adjustment-board/" },
  "Marion": { vabName: "Marion County Clerk of Court and Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 1030", city: "Ocala", state: "FL", zip: "34478-1030", confidence: "confirmed", sourceUrl: "https://www.marioncountyclerk.org/departments/records-recording/value-adjustment-board/", note: "POSTMARK NOT SUFFICIENT — must be received. Hand delivery: 19 N Pine Avenue, 3rd Floor, Ocala, FL 34475" },
  "Martin": { vabName: "Martin County Clerk of the Circuit Court – Value Adjustment Board", attn: "Value Adjustment Board", street: "P.O. Box 9016", city: "Stuart", state: "FL", zip: "34995", confidence: "confirmed", sourceUrl: "https://www.martinclerk.com/188/Value-Adjustment-Board", note: "Hand delivery: 100 SE Ocean Blvd, Stuart, FL 34994" },
  "Miami-Dade": { vabName: "Clerk of the Value Adjustment Board – Stephen P. Clark Center", attn: "Value Adjustment Board", street: "111 NW First Street, Suite 1720", city: "Miami", state: "FL", zip: "33128", confidence: "confirmed", sourceUrl: "https://www.miamidadeclerk.gov/clerk/value-adjustment-board.page" },
  "Monroe": { vabName: "Monroe County Clerk of the Circuit Court – Clerk, Value Adjustment Board", attn: "Clerk, Value Adjustment Board", street: "P.O. Box 1980", city: "Key West", state: "FL", zip: "33041", confidence: "confirmed", sourceUrl: "https://www.mcpafl.org/appraisal/appeals-vab/" },
  "Nassau": { vabName: "Nassau County Clerk of Courts – VAB Clerk", attn: "Attn: VAB Clerk", street: "76347 Veterans Way", city: "Yulee", state: "FL", zip: "32097", confidence: "confirmed", sourceUrl: "https://ncpafl.com/general-info/value-adjustment-board/", note: "Address read back and confirmed by phone 13 Aug 2026 (Nathan) — unchanged. The fee and payee were corrected on the same call; see lib/flCountyFees.js. VAB contact: vab@nassauclerk.com, 904-548-4660." },
  "Okaloosa": { vabName: "Okaloosa County Clerk of Court and Comptroller – VAB Clerk", attn: "Attn: VAB Clerk", street: "101 E James Lee Blvd", city: "Crestview", state: "FL", zip: "32536", confidence: "confirmed", sourceUrl: "https://okaloosaclerk.com/board-services/value-adjustment-board/" },
  "Okeechobee": { vabName: "Okeechobee County Clerk of Circuit Court and Comptroller – Clerk to the Board", attn: "Clerk to the Board, Room 222", street: "304 NW 2nd Street, Room 222", city: "Okeechobee", state: "FL", zip: "34972", confidence: "confirmed", sourceUrl: "https://myokeeclerk.com/vab" },
  "Orange": { vabName: "Orange County Comptroller – Orange County Value Adjustment Board", attn: "Orange County Value Adjustment Board", street: "P.O. Box 38", city: "Orlando", state: "FL", zip: "32802-0038", confidence: "confirmed", sourceUrl: "https://www.occompt.com/199/Value-Adjustment-Board", note: "VAB clerk is the COMPTROLLER, not the Clerk of Court." },
  "Osceola": { vabName: "Osceola Clerk of the Circuit Court & County Comptroller – VAB Clerk", attn: "Attn: VAB Clerk", street: "2 Courthouse Square, Office 2707", city: "Kissimmee", state: "FL", zip: "34741", confidence: "confirmed", sourceUrl: "https://osceolaclerk.com/value-adjustment-board/" },
  "Palm Beach": { vabName: "Palm Beach County Value Adjustment Board", attn: "Palm Beach County Value Adjustment Board", street: "P.O. Box 4036", city: "West Palm Beach", state: "FL", zip: "33402", confidence: "confirmed", sourceUrl: "https://www.mypalmbeachclerk.com/departments/value-adjustment-board-vab/petition-filing", note: "Hand delivery: 301 North Olive Ave, Room 206, West Palm Beach, FL 33401" },
  "Pasco": { vabName: "Pasco County Clerk & Comptroller – Value Adjustment Board, c/o Board Records Division", attn: "Value Adjustment Board, c/o Board Records Division", street: "14236 6th Street, Suite 201", city: "Dade City", state: "FL", zip: "33523", confidence: "confirmed", sourceUrl: "https://www.pascoclerk.com/307/Value-Adjustment-Board", note: "POSTMARK NOT SUFFICIENT — Pasco states postmarked petitions are untimely." },
  "Pinellas": { vabName: "Pinellas County Value Adjustment Board, c/o Clerk of the Circuit Court – Board Records", attn: "Pinellas County Value Adjustment Board, c/o Board Records Department", street: "315 Court Street, Fifth Floor", city: "Clearwater", state: "FL", zip: "33756", confidence: "confirmed", sourceUrl: "https://vabpetitions.mypinellasclerk.gov/" },
  "Polk": { vabName: "Polk County Value Adjustment Board", attn: "Attn: Comptroller VAB Clerk", street: "P.O. Box 988", city: "Bartow", state: "FL", zip: "33831", confidence: "confirmed", sourceUrl: "https://www.polkclerkfl.gov/196/Value-Adjustment-Board" },
  "Putnam": { vabName: "Putnam County Clerk of the Circuit Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 758", city: "Palatka", state: "FL", zip: "32178", confidence: "confirmed", sourceUrl: "https://putnamclerk.com/county-comptroller/value-adjustment-board/" },
  "St. Johns": { vabName: "St. Johns County Clerk of the Circuit Court and County Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "4010 Lewis Speedway", city: "St. Augustine", state: "FL", zip: "32084", confidence: "confirmed", sourceUrl: "https://stjohnsclerk.com/" },
  "St. Lucie": { vabName: "St. Lucie County Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "201 S. Indian River Drive", city: "Fort Pierce", state: "FL", zip: "34950", confidence: "confirmed", sourceUrl: "https://slcvab.stlucieco.gov/axiaweb2026/", note: "CORRECTED 2026-09-01 after a live rejection. Both the payee AND this address were wrong while marked confirmed. The held address 2300 Virginia Avenue 34982 is the Clerk of the Circuit Court; the VAB publishes 201 S. Indian River Drive, Fort Pierce 34950 on its own petition portal. VERIFY BY PHONE 772-462-1429 before the next mailing." },
  "Santa Rosa": { vabName: "Santa Rosa County Clerk of Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "6495 Caroline St., Suite A", city: "Milton", state: "FL", zip: "32570", confidence: "confirmed", sourceUrl: "https://santarosaclerk.com/other-services/value-adjustment-board-public-notice/" },
  "Sarasota": { vabName: "Sarasota Clerk of the Circuit Court and County Comptroller – Clerk to the Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "1 Apex Rd", city: "Sarasota", state: "FL", zip: "34240", confidence: "confirmed", sourceUrl: "https://www.sarasotaclerk.com/Home-and-Property/Value-Adjustment-Board", note: "CONFIRMED BY PHONE 2026-08-06 (Nathan). The county gave 1 Apex Rd, Sarasota FL 34240 — NOT the P.O. Box 3079 that two official web sources listed — and the payee as Board of County Commissioners, not the Clerk of Court. Both differ from what the Clerk's own VAB page publishes; the phone answer is taken as authoritative over the website." },
  "Seminole": { vabName: "Seminole County Clerk of the Circuit Court & Comptroller – VAB Office", attn: "Attn: Clerk's Administration – Value Adjustment Board", street: "91 Eslinger Way", city: "Sanford", state: "FL", zip: "32773", confidence: "confirmed", sourceUrl: "https://www.seminoleclerk.org/value-adjustment-board/" },
  "Sumter": { vabName: "Sumter County Value Adjustment Board, c/o Clerk of the Circuit Court", attn: "Value Adjustment Board, c/o Clerk of the Circuit Court", street: "P.O. Box 247", city: "Bushnell", state: "FL", zip: "33513", confidence: "confirmed", sourceUrl: "https://www.sumterclerk.com/value-adjustment-board" },
  "Suwannee": { vabName: "Suwannee County Clerk of the Circuit Court – Clerk of the Value Adjustment Board", attn: "Attn: Clerk of the Value Adjustment Board", street: "200 South Ohio Avenue", city: "Live Oak", state: "FL", zip: "32064", confidence: "confirmed", sourceUrl: "https://www.suwgov.org/county-comptroller/value-adjustment-board/" },
  "Taylor": { vabName: "Taylor County Clerk of the Circuit Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "108 North Jefferson Street, Suite 102", city: "Perry", state: "FL", zip: "32347", confidence: "confirmed", sourceUrl: "https://taylorclerk.com/departments/value-adjustment-board/" },
  "Union": { vabName: "Union County Clerk of Courts & Comptroller – Clerk to the Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "55 West Main Street, Room 103", city: "Lake Butler", state: "FL", zip: "32054", confidence: "unconfirmed", sourceUrl: "https://unionclerk.com/value-adjustment-board/", note: "No dedicated petition mailing address published. Confirm by phone." },
  "Volusia": { vabName: "Volusia County Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "123 W. Indiana Ave., Suite 301", city: "DeLand", state: "FL", zip: "32720", confidence: "confirmed", sourceUrl: "https://www.volusia.org/government/county-council/advisory-boards/value-adjustment-board.stml", note: "CONFIRMED BY PHONE 2026-08-06 (Nathan). Suite 301 and payee County of Volusia both confirmed exactly as held — the brochure saying Suite 304 was indeed stale." },
  "Wakulla": { vabName: "Wakulla County Clerk of Circuit Court & Comptroller – Clerk of the Value Adjustment Board", attn: "Clerk of the Value Adjustment Board", street: "3056 Crawfordville Highway, Room 129", city: "Crawfordville", state: "FL", zip: "32327", confidence: "confirmed", sourceUrl: "https://wakullaclerk.org/clerk_to_the_board/value_adjustment_board.php" },
  "Walton": { vabName: "Walton County Clerk of Courts & Comptroller – VAB Clerk", attn: "Attn: Value Adjustment Board", street: "571 US Highway 90 East", city: "DeFuniak Springs", state: "FL", zip: "32433", confidence: "confirmed", sourceUrl: "https://waltonclerkfl.gov/vab", note: "CONFIRMED BY PHONE 2026-08-06 (Nathan). The street address is correct and the P.O. Box 1260 on the Property Appraiser site is NOT where petitions go. Attn line confirmed as required. Source URL moved from waltonpa.com to the Clerk's own VAB page." },
  "Washington": { vabName: "Washington County Clerk of Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 647", city: "Chipley", state: "FL", zip: "32428", confidence: "confirmed", sourceUrl: "https://www.washingtonclerk.com/additional-informationuseful-links/value-adjustment-board/", note: "Physical: 1293 Jackson Avenue, Suite 101, Chipley, FL 32428" },
};

/** Normalize a county name to the table's key format. */
function normalizeCounty(countyName) {
  if (!countyName) return '';
  let c = String(countyName).replace(/\s+County$/i, '').trim();
  // Common variants returned by geocoders and LLM fallbacks.
  const aliases = {
    'saint johns': 'St. Johns', 'st johns': 'St. Johns', 'st. johns': 'St. Johns',
    'saint lucie': 'St. Lucie', 'st lucie': 'St. Lucie', 'st. lucie': 'St. Lucie',
    'miami dade': 'Miami-Dade', 'miami-dade': 'Miami-Dade', 'miamidade': 'Miami-Dade', 'dade': 'Miami-Dade',
    'desoto': 'DeSoto', 'de soto': 'DeSoto',
    'indian river': 'Indian River', 'palm beach': 'Palm Beach', 'santa rosa': 'Santa Rosa',
  };
  const key = c.toLowerCase();
  if (aliases[key]) return aliases[key];
  // Title-case fallback so "ORANGE" and "orange" both resolve.
  // Title-case each ALPHA RUN, not each whitespace-delimited token. `\w\S*`
  // swallowed the hyphen, so "Miami-Dade" normalized to "Miami-dade" — which
  // matched no key in either table, so getFlVabAddress returned null and Florida's
  // LARGEST county was hard-blocked at checkout as "not verified".
  return c.replace(/[A-Za-z]+/g, (t) => t.charAt(0).toUpperCase() + t.slice(1).toLowerCase());
}

/**
 * Get the VAB Clerk mailing address for a Florida county.
 * Returns null if the county is unknown OR unconfirmed — callers MUST treat
 * null as "cannot file" and must never substitute another address.
 */
export function getFlVabAddress(countyName) {
  const entry = FL_VAB_ADDRESSES[normalizeCounty(countyName)];
  if (!entry) return null;
  if (entry.confidence !== 'confirmed') return null;
  return entry;
}

/**
 * ============================================================================
 * LOB CAPS address_line1 + address_line2 AT 50 CHARACTERS, COMBINED.
 * ============================================================================
 * 25 Aug 2026, 10:59Z, order db86d957 — the first paying customer:
 *
 *   The sum (51) of to.address_line1 (601 E KENNEDY BLVD FL 12) and
 *   to.address_line2 (ATTN VALUE ADJUSTMENT BOARD) cannot surpass 50 characters
 *
 * One character over. The card had already been charged, fulfilment threw, the
 * order went to needs_review, and the portal correctly told her we had hit a
 * problem. Money taken, petition not mailed, thirteen days to a
 * receipt-not-postmark deadline.
 *
 * TWO THINGS MADE THIS WORSE THAN A BAD RECORD.
 *
 * First, LOB NORMALISES BEFORE IT MEASURES. We store "601 East Kennedy Blvd,
 * Floor 12" and "Attn: Value Adjustment Board" — 58 characters raw. Lob upcases,
 * strips punctuation and applies USPS abbreviations (East->E, Boulevard->BLVD,
 * Floor->FL), giving 51. So the number that matters is not the one visible in
 * this file, and eyeballing these strings does not tell you whether an order
 * will mail.
 *
 * Second, IT IS NOT ONE COUNTY. Measured across all 61 confirmed entries on
 * 25 Aug, 23 EXCEED THE CAP — Pinellas (85), Leon (73), Pasco (69), Seminole,
 * Columbia, Wakulla, Escambia, Sumter, Hamilton, Duval, Glades, Bay, Collier,
 * Hardee, Hernando, Suwannee, Calhoun, Taylor, Palm Beach, Volusia, Clay,
 * Flagler, Hillsborough. Every order in any of them would have failed the same
 * way, after payment. Hillsborough was simply the first county anyone bought in.
 *
 * WHAT THIS DOES. Produces the two recipient lines Lob will accept, shedding the
 * least load-bearing text first and stopping as soon as it fits:
 *
 *   1. As stored.
 *   2. Drop the "Attn:" prefix — the cheque's payee NAME already carries the
 *      office, so the word itself is overhead.
 *   3. Abbreviate "Value Adjustment Board" to "VAB" — understood by the clerk's
 *      office that receives these, which is the only reader that matters.
 *   4. Drop line 2 entirely. USPS routes on line 1 and the payee name; the
 *      attention line is routing help inside the building, not addressing.
 *
 * IT NEVER TRUNCATES. A cut string can name a different place — "601 E KENNEDY
 * BLVD FL 1" is a real floor and the wrong one — and this address decides where
 * a sworn petition and a cheque physically land. Dropping a whole component is
 * recoverable; a silently wrong one is not.
 *
 * scripts/verify-fl-dispatch.mjs asserts EVERY confirmed county fits after this,
 * so a new address that would blow the cap fails the build instead of failing a
 * customer's order after their card is charged.
 */
export const LOB_ADDRESS_LINE_BUDGET = 50;

/**
 * THE LADDER AIMS BELOW THE CAP, ON PURPOSE.
 *
 * lobNormalizeLine is an INFERENCE of Lob's normalisation, and it is validated
 * against exactly one real sample — the Hillsborough failure, where it
 * reproduces Lob's own reported strings and its 51 character for character.
 * That is good evidence and it is one data point.
 *
 * Aiming at exactly 50 left Collier, Pasco and Pinellas sitting on 50 with zero
 * headroom, so a single token I have guessed wrong — Lob keeping a comma, or
 * expanding "c/o", or an abbreviation not in the table below — reproduces this
 * incident in a different county, after a card is charged.
 *
 * Three characters of margin costs a slightly shorter attention line on a
 * handful of envelopes. Not having it costs an order. Assertions still measure
 * against the true cap of 50; only the shedding decision uses this.
 */
export const LOB_LINE_SAFETY_MARGIN = 3;
export const LOB_LINE_TARGET = LOB_ADDRESS_LINE_BUDGET - LOB_LINE_SAFETY_MARGIN;

const LOB_ABBR = {
  EAST: 'E', WEST: 'W', NORTH: 'N', SOUTH: 'S', NORTHEAST: 'NE', NORTHWEST: 'NW',
  SOUTHEAST: 'SE', SOUTHWEST: 'SW', BOULEVARD: 'BLVD', STREET: 'ST', AVENUE: 'AVE',
  ROAD: 'RD', DRIVE: 'DR', FLOOR: 'FL', SUITE: 'STE', ROOM: 'RM', BUILDING: 'BLDG',
  COURT: 'CT', PLACE: 'PL', LANE: 'LN', HIGHWAY: 'HWY', PARKWAY: 'PKWY',
  TERRACE: 'TER', CIRCLE: 'CIR', ATTENTION: 'ATTN',
};

/**
 * Approximate Lob's own normalisation closely enough to PREDICT its cap.
 *
 * Deliberately conservative: it decides whether to shed a component, and
 * over-estimating a length costs a dropped "Attn:" while under-estimating costs
 * a failed mailing after payment. The lines we SEND are the un-normalised ones —
 * Lob does its own normalisation; this only measures.
 */
export function lobNormalizeLine(s) {
  return String(s || '')
    .toUpperCase()
    .replace(/[.,#:]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .split(' ')
    .map((w) => LOB_ABBR[w] || w)
    .join(' ');
}

export function lobLineLength(line1, line2) {
  return lobNormalizeLine(line1).length + lobNormalizeLine(line2).length;
}

/**
 * The recipient lines to hand Lob, guaranteed to fit its combined cap.
 *
 * Returns { line1, line2, shed } — `shed` names what was given up, so
 * send-letter can log it and an operator can see why an envelope reads
 * differently from this file. Returns null only if line 1 alone is over, which
 * the build forbids.
 */
export function flVabMailingLines(countyName) {
  const entry = getFlVabAddress(countyName);
  if (!entry) return null;

  const line1 = entry.street;
  const attn = entry.attn || '';
  const noPrefix = attn.replace(/^\s*attn:?\s*/i, '');
  const vab = noPrefix.replace(/value adjustment board/gi, 'VAB');
  /**
   * The county's own name, dropped LAST among the shortenings and only when
   * "VAB" alone was not enough. It is the most redundant token on the envelope —
   * the city, state and ZIP beneath it already say which county this is — but it
   * is dropped after the abbreviation because "Palm Beach County VAB" is more
   * useful to a mailroom than a bare "VAB" when both would fit.
   *
   * This rung exists for Pinellas, whose attention line is 67 characters
   * ("Pinellas County Value Adjustment Board c/o Board Records Department").
   * Without it Pinellas was the one county that lost its line 2 outright — and
   * "c/o Board Records Department" is exactly the part that gets a petition to
   * the right desk. With it, Pinellas lands on 50 and keeps the routing.
   */
  const noCounty = vab.replace(
    new RegExp(`^\\s*${normalizeCounty(countyName).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s+county\\s+`, 'i'),
    ''
  );

  /**
   * Ordinary office words, abbreviated the way a mailroom already writes them.
   * This rung exists so Pinellas and Pasco keep their "c/o <desk>" routing
   * instead of falling through to a bare line — that clause is the difference
   * between a petition reaching the Board Records desk and reaching a mailroom.
   */
  const shortWords = (s) => s
    .replace(/\bDepartment\b/gi, 'Dept')
    .replace(/\bDivision\b/gi, 'Div')
    .replace(/\bAdministration\b/gi, 'Admin')
    .replace(/\bCircuit Court\b/gi, 'Circuit Ct');

  const candidates = [
    { line2: attn, shed: null },
    { line2: noPrefix, shed: 'the "Attn:" prefix' },
    { line2: vab, shed: '"Attn:" and "Value Adjustment Board" shortened to "VAB"' },
    { line2: shortWords(vab), shed: '"Attn:", "VAB", and office words abbreviated' },
    { line2: shortWords(noCounty), shed: '"Attn:", the county name, "VAB", and office words abbreviated' },
    { line2: '', shed: 'the attention line entirely — line 1 and the payee name carry it' },
  ];

  for (const c of candidates) {
    if (lobLineLength(line1, c.line2) <= LOB_LINE_TARGET) {
      return { line1, line2: c.line2 || undefined, shed: c.shed };
    }
  }
  return null;
}

/** Raw lookup including unconfirmed entries — for admin/ops tooling only. */
export function getFlVabAddressRaw(countyName) {
  return FL_VAB_ADDRESSES[normalizeCounty(countyName)] || null;
}

/** True only if we can safely mail a petition for this county today. */
export function isFlCountySupported(countyName) {
  return getFlVabAddress(countyName) !== null;
}

/** True if this county requires physical receipt (postmark not sufficient). */
export function flCountyRequiresReceipt(countyName) {
  return FL_POSTMARK_NOT_ACCEPTED.includes(normalizeCounty(countyName));
}

/** Counties currently blocked pending phone verification. */
/**
 * All 67 Florida county names, sorted. Used to populate the county picker in the
 * apply funnel so a customer can correct or supply their county when the Census
 * geocoder cannot place the address — a DROPDOWN, never free text, because a
 * typo here mails the petition and the fee cheque to the wrong government office.
 */
export const FL_COUNTY_NAMES = Object.keys(FL_VAB_ADDRESSES).sort((a, b) => a.localeCompare(b));

export function getUnconfirmedFlCounties() {
  return Object.entries(FL_VAB_ADDRESSES)
    .filter(([, v]) => v.confidence !== 'confirmed')
    .map(([k]) => k);
}

export default FL_VAB_ADDRESSES;
