/**
 * Florida Value Adjustment Board (VAB) Clerk mailing addresses — all 67 counties.
 *
 * WHY THIS FILE EXISTS:
 * A DR-486 petition and its filing-fee check must be mailed to the CLERK OF THE
 * VALUE ADJUSTMENT BOARD — *not* to the county Property Appraiser. Mailing to the
 * Property Appraiser means the petition is never filed and the customer loses the
 * appeal year. Before this file existed, the destination address was generated by
 * an LLM at request time and cached in Redis for 180 days, unvalidated. That is
 * never acceptable for addressing government mail. This table is the single source
 * of truth and the filing path must not fall back to any other source.
 *
 * DO NOT GUESS. If a county is not `confirmed` below, orders for that county are
 * blocked at checkout (see isFlCountySupported). A blocked sale is recoverable;
 * a misdelivered petition is not.
 *
 * NOTE — non-obvious VAB clerks (these are NOT the Clerk of the Circuit Court):
 *   Orange   → Orange County Comptroller
 *   Duval    → City of Jacksonville, City Hall
 *   Broward  → County VAB office, Governmental Center Room 120
 *   Volusia  → County Council administration building
 *   Pasco    → Board Records Division
 *   Pinellas → Board Records Department
 *
 * Researched 2026-07-28 from official county government sources. Each entry
 * carries the sourceUrl it was verified against.
 *
 * REVIEW REMINDER: the 12 `unconfirmed` counties each need one phone call to the
 * VAB clerk to confirm the petition mailing address. Until then they are blocked.
 */

// Counties that require PHYSICAL RECEIPT by the deadline and explicitly state
// that a postmark is NOT sufficient. These need extra lead time before the
// deadline — see lib/filingWindows.js.
export const FL_POSTMARK_NOT_ACCEPTED = ['Pasco', 'Marion'];

const FL_VAB_ADDRESSES = {
  "Alachua": { vabName: "Alachua County Clerk of Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "12 SE 1st Street, 4th Floor", city: "Gainesville", state: "FL", zip: "32601", confidence: "confirmed", sourceUrl: "https://alachuacounty.us/depts/clerk/vab/pages/valueadjustmentboard.aspx" },
  "Baker": { vabName: "Baker County Clerk of the Circuit Court – Clerk to the VAB", attn: "Attn: VAB", street: "339 E Macclenny Avenue", city: "Macclenny", state: "FL", zip: "32063", confidence: "confirmed", sourceUrl: "https://bakerclerk.com/vab/" },
  "Bay": { vabName: "Bay County Clerk of Court & Comptroller – Clerk of the Value Adjustment Board", attn: "Attn: Clerk of the Value Adjustment Board", street: "225 McKenzie Avenue", city: "Panama City", state: "FL", zip: "32401", confidence: "confirmed", sourceUrl: "https://www.baycoclerk.com/clerk-services/value-adjustment-board/" },
  "Bradford": { vabName: "Bradford County Clerk of the Circuit Court & Comptroller – Clerk to the VAB", attn: "Attn: Value Adjustment Board", street: "P.O. Drawer B", city: "Starke", state: "FL", zip: "32091", confidence: "unconfirmed", sourceUrl: "https://bradfordclerk.com/value-adjustment-board/when-and-how-to-file-your-vab-petition/", note: "No dedicated petition mailing address published. Confirm by phone." },
  "Brevard": { vabName: "Brevard County Clerk of Courts – Value Adjustment Board", attn: "Value Adjustment Board", street: "P.O. Box 999", city: "Titusville", state: "FL", zip: "32781-0999", confidence: "confirmed", sourceUrl: "http://www.brevardclerk.us/file-a-petition" },
  "Broward": { vabName: "Broward County Value Adjustment Board", attn: "Value Adjustment Board", street: "115 S. Andrews Avenue, Room 120", city: "Fort Lauderdale", state: "FL", zip: "33301", confidence: "confirmed", sourceUrl: "https://www.broward.org/VAB/Pages/FilingAPetition.aspx" },
  "Calhoun": { vabName: "Calhoun County Clerk of Circuit Court – Clerk to the Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "20859 Central Ave. East, Room 130", city: "Blountstown", state: "FL", zip: "32424", confidence: "confirmed", sourceUrl: "https://calhounclerk.com/clerk-to-the-board/value-adjustment-board/" },
  "Charlotte": { vabName: "Charlotte County Value Adjustment Board", attn: "Value Adjustment Board", street: "18500 Murdock Circle, Room 416", city: "Port Charlotte", state: "FL", zip: "33948", confidence: "confirmed", sourceUrl: "https://charlotteclerk.com/departments/vab/" },
  "Citrus": { vabName: "Citrus County Clerk of Courts – Value Adjustment Board", attn: "Attn: VAB", street: "110 N Apopka Avenue", city: "Inverness", state: "FL", zip: "34450", confidence: "confirmed", sourceUrl: "https://citrusclerk.org/216/Value-Adjustment-Board" },
  "Clay": { vabName: "Clay County Clerk of Court & Comptroller – Clerk to the Value Adjustment Board", attn: "Attn: Clerk to the Value Adjustment Board", street: "P.O. Box 698", city: "Green Cove Springs", state: "FL", zip: "32043", confidence: "confirmed", sourceUrl: "https://clayclerk.com/departments/value-adjustment-board/petitions-appeals-forms/" },
  "Collier": { vabName: "Collier County Clerk of the Circuit Court – Board Minutes & Records (VAB)", attn: "Attn: Value Adjustment Board", street: "3299 Tamiami Trail East, Suite 401", city: "Naples", state: "FL", zip: "34112-5746", confidence: "confirmed", sourceUrl: "https://www.collierclerk.com/board-records-vab/value-adjustment-board/" },
  "Columbia": { vabName: "Columbia County Clerk of the Circuit Court & Comptroller – Clerk to VAB", attn: "Attn: Clerk to the Value Adjustment Board", street: "173 NE Hernando Avenue, Room 225", city: "Lake City", state: "FL", zip: "32055", confidence: "confirmed", sourceUrl: "https://columbiaclerk.com/value-adjustment-board/" },
  "DeSoto": { vabName: "DeSoto County Clerk of the Circuit Court – Clerk to the VAB", attn: "Attn: Value Adjustment Board", street: "115 East Oak Street, Room 101", city: "Arcadia", state: "FL", zip: "34266", confidence: "unconfirmed", sourceUrl: "https://www.desotoclerk.com/contact/", note: "No dedicated petition mailing address published. Confirm by phone." },
  "Dixie": { vabName: "Dixie County Clerk of Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 1206", city: "Cross City", state: "FL", zip: "32628", confidence: "unconfirmed", sourceUrl: "https://dixieclerk.com/value-adjustment-board-forms", note: "No dedicated petition mailing address published. Confirm by phone." },
  "Duval": { vabName: "Clerk of the Value Adjustment Board – City of Jacksonville", attn: "Clerk of the Value Adjustment Board", street: "117 West Duval Street, Suite 305", city: "Jacksonville", state: "FL", zip: "32202", confidence: "confirmed", sourceUrl: "https://www.jacksonville.gov/departments/boards-and-commissions/value-adjustment-board" },
  "Escambia": { vabName: "Escambia County Clerk of the Circuit Court and Comptroller – Clerk to the VAB", attn: "Attn: Clerk to the Value Adjustment Board", street: "221 Palafox Place, Suite 110", city: "Pensacola", state: "FL", zip: "32502-5843", confidence: "confirmed", sourceUrl: "https://www.escambiaclerk.com/264/Value-Adjustment-Board-VAB-Information-a" },
  "Flagler": { vabName: "Flagler County Clerk & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "1769 E Moody Blvd, Bldg 1", city: "Bunnell", state: "FL", zip: "32110", confidence: "confirmed", sourceUrl: "https://flaglerclerk.gov/vab/" },
  "Franklin": { vabName: "Franklin County Clerk of the Circuit Court & Comptroller", attn: "Attn: Value Adjustment Board", street: "33 Market Street, Suite 203", city: "Apalachicola", state: "FL", zip: "32320", confidence: "unconfirmed", sourceUrl: "https://www.franklinclerk.com/clerk-services/bocc-records/", note: "No dedicated petition mailing address published. Confirm by phone." },
  "Gadsden": { vabName: "Gadsden County Clerk of the Circuit Court", attn: "Attn: Value Adjustment Board", street: "P.O. Box 1649", city: "Quincy", state: "FL", zip: "32353-1649", confidence: "unconfirmed", sourceUrl: "https://www.fl-counties.com/directory-results/?county=Gadsden%20County", note: "Not verified on an official VAB page. Physical: 10 E Jefferson St, Quincy, FL 32351. Confirm by phone." },
  "Gilchrist": { vabName: "Gilchrist County Clerk of the Circuit Court & Comptroller – Clerk to the VAB", attn: "Attn: Value Adjustment Board", street: "P.O. Box 37", city: "Trenton", state: "FL", zip: "32693", confidence: "unconfirmed", sourceUrl: "https://gilchristclerk.com/value-adjustment-board/", note: "No dedicated petition mailing address published. Physical: 112 S. Main St. Confirm by phone." },
  "Glades": { vabName: "Glades County Clerk of the Circuit Court & Comptroller – Clerk to the VAB", attn: "Attn: Clerk to the Value Adjustment Board", street: "500 Avenue J, Suite 102", city: "Moore Haven", state: "FL", zip: "33471", confidence: "confirmed", sourceUrl: "https://gladesclerk.com/clerk-services/value-adjustment-board/" },
  "Gulf": { vabName: "Gulf County Clerk of the Circuit Court – VAB Clerk", attn: "Attn: VAB Clerk", street: "1000 Cecil G. Costin, Sr. Blvd., Room 149", city: "Port St. Joe", state: "FL", zip: "32456", confidence: "confirmed", sourceUrl: "https://www.gulfclerk.com/value-adjustment-board/" },
  "Hamilton": { vabName: "Hamilton County Clerk of Circuit Court – Clerk of the Value Adjustment Board", attn: "Attn: Clerk of the Value Adjustment Board", street: "207 NE 1st Street, Room 106", city: "Jasper", state: "FL", zip: "32052", confidence: "confirmed", sourceUrl: "https://hamiltonclerk.com/value-adjustment-board/" },
  "Hardee": { vabName: "Hardee County Clerk of the Circuit Court and Comptroller – VAB Clerk", attn: "Attn: Value Adjustment Board Clerk", street: "417 West Main Street, Suite 202", city: "Wauchula", state: "FL", zip: "33873", confidence: "unconfirmed", sourceUrl: "https://www.hardeeclerk.com/departments/value-adjustment-board/information/", note: "No dedicated petition mailing address published. Confirm by phone." },
  "Hendry": { vabName: "Hendry County Clerk of Circuit Court – Value Adjustment Board", attn: "Value Adjustment Board", street: "P.O. Box 1760", city: "LaBelle", state: "FL", zip: "33975", confidence: "confirmed", sourceUrl: "https://www.hendryclerk.org/value-adjustment-board/", note: "Courier/FedEx/UPS: 25 E. Hickpochee Ave., LaBelle, FL 33935" },
  "Hernando": { vabName: "Hernando County Clerk of Circuit Court & Comptroller – Clerk to the VAB", attn: "Clerk to the Value Adjustment Board", street: "20 N. Main Street, Room 362", city: "Brooksville", state: "FL", zip: "34601", confidence: "confirmed", sourceUrl: "https://hernandoclerk.com/county-services/value-adjustment-board/" },
  "Highlands": { vabName: "Highlands County Clerk of Courts – Value Adjustment Board", attn: "Attn: Value Adjustment Clerk", street: "590 S Commerce Avenue", city: "Sebring", state: "FL", zip: "33870", confidence: "confirmed", sourceUrl: "https://www.highlandsclerkfl.gov/clerk_to_the_board/value_adjustment_board/index.php" },
  "Hillsborough": { vabName: "Hillsborough County Clerk of Circuit Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "601 East Kennedy Blvd, Floor 12", city: "Tampa", state: "FL", zip: "33602", confidence: "confirmed", sourceUrl: "https://www.hillsclerk.com/about-us/forms/value-adjustment-board-forms" },
  "Holmes": { vabName: "Holmes County Clerk's Finance Office – Value Adjustment Board", attn: "Attn: VAB", street: "201 N. Oklahoma Street, Suite 205", city: "Bonifay", state: "FL", zip: "32425", confidence: "confirmed", sourceUrl: "https://holmesclerk.com/other-services/value-adjustment-board/" },
  "Indian River": { vabName: "Indian River County Value Adjustment Board – Clerk to the Board", attn: "Attn: Value Adjustment Board", street: "1801 27th Street, A2-801", city: "Vero Beach", state: "FL", zip: "32960", confidence: "confirmed", sourceUrl: "https://vab.indian-river.org/" },
  "Jackson": { vabName: "Jackson County Clerk of the Circuit Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Drawer 510", city: "Marianna", state: "FL", zip: "32447", confidence: "confirmed", sourceUrl: "https://www.jacksonclerk.com/clerk-services/value-adjustment-board/", note: "Physical: 4445 Lafayette Street, Marianna, FL 32446" },
  "Jefferson": { vabName: "Jefferson County Clerk of the Circuit Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "1 Courthouse Circle", city: "Monticello", state: "FL", zip: "32344", confidence: "confirmed", sourceUrl: "https://www.jeffersonclerk.com/clerk-services/value-adjustment-board/" },
  "Lafayette": { vabName: "Lafayette County Clerk of Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 88", city: "Mayo", state: "FL", zip: "32066", confidence: "confirmed", sourceUrl: "https://www.lafayetteclerk.com/departments-services/clerk-services/value-adjustment-board/" },
  "Lake": { vabName: "Lake County Clerk of the Circuit Court & Comptroller – Value Adjustment Board", attn: "Value Adjustment Board", street: "P.O. Box 7800", city: "Tavares", state: "FL", zip: "32778", confidence: "confirmed", sourceUrl: "https://www.lakecountyclerkfl.gov/" },
  "Lee": { vabName: "Lee County Clerk of Court – Value Adjustment Board", attn: "Value Adjustment Board", street: "P.O. Box 2469", city: "Fort Myers", state: "FL", zip: "33902", confidence: "confirmed", sourceUrl: "https://www.leeclerk.org/departments/value-adjustment-board-vab" },
  "Leon": { vabName: "Leon County Clerk of Court – Value Adjustment Board", attn: "Attn: Clerk Finance Department / Value Adjustment Board", street: "301 S. Monroe Street, #100", city: "Tallahassee", state: "FL", zip: "32301", confidence: "confirmed", sourceUrl: "https://cvweb.leonclerk.com/public/clerk_services/administration/value_adjustment_board/vab.asp" },
  "Levy": { vabName: "Levy County Clerk of the Circuit Court – Value Adjustment Board", attn: "Attn: VAB Clerk", street: "355 South Court Street", city: "Bronson", state: "FL", zip: "32621", confidence: "confirmed", sourceUrl: "https://www.levyclerk.com/value-adjustment-board/" },
  "Liberty": { vabName: "Liberty County Clerk of Circuit Court & County Comptroller – Clerk to the VAB", attn: "Attn: Value Adjustment Board", street: "P.O. Box 399", city: "Bristol", state: "FL", zip: "32321", confidence: "confirmed", sourceUrl: "https://libertycountyfl.org/value-adjustment-board/", note: "Physical: 10818 NW SR 20, Bristol, FL 32321" },
  "Madison": { vabName: "Madison County Clerk of Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 237", city: "Madison", state: "FL", zip: "32341", confidence: "unconfirmed", sourceUrl: "https://www.madisonclerk.com/departments-services/departments/value-adjustment-board/", note: "No dedicated petition mailing address published. Physical: 125 SW Range Ave. Confirm by phone." },
  "Manatee": { vabName: "Manatee County Clerk of the Circuit Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 25400", city: "Bradenton", state: "FL", zip: "34206", confidence: "confirmed", sourceUrl: "https://www.manateeclerk.com/departments/value-adjustment-board/" },
  "Marion": { vabName: "Marion County Clerk of Court and Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 1030", city: "Ocala", state: "FL", zip: "34478-1030", confidence: "confirmed", sourceUrl: "https://www.marioncountyclerk.org/departments/records-recording/value-adjustment-board/", note: "POSTMARK NOT SUFFICIENT — must be received. Hand delivery: 19 N Pine Avenue, 3rd Floor, Ocala, FL 34475" },
  "Martin": { vabName: "Martin County Clerk of the Circuit Court – Value Adjustment Board", attn: "Value Adjustment Board", street: "P.O. Box 9016", city: "Stuart", state: "FL", zip: "34995", confidence: "confirmed", sourceUrl: "https://www.martinclerk.com/188/Value-Adjustment-Board", note: "Hand delivery: 100 SE Ocean Blvd, Stuart, FL 34994" },
  "Miami-Dade": { vabName: "Clerk of the Value Adjustment Board – Stephen P. Clark Center", attn: "Value Adjustment Board", street: "111 NW First Street, Suite 1720", city: "Miami", state: "FL", zip: "33128", confidence: "confirmed", sourceUrl: "https://www.miamidadeclerk.gov/clerk/value-adjustment-board.page" },
  "Monroe": { vabName: "Monroe County Clerk of the Circuit Court – Clerk, Value Adjustment Board", attn: "Clerk, Value Adjustment Board", street: "P.O. Box 1980", city: "Key West", state: "FL", zip: "33041", confidence: "confirmed", sourceUrl: "https://www.mcpafl.org/appraisal/appeals-vab/" },
  "Nassau": { vabName: "Nassau County Clerk of Courts – VAB Clerk", attn: "Attn: VAB Clerk", street: "76347 Veterans Way", city: "Yulee", state: "FL", zip: "32097", confidence: "confirmed", sourceUrl: "https://ncpafl.com/general-info/value-adjustment-board/" },
  "Okaloosa": { vabName: "Okaloosa County Clerk of Court and Comptroller – VAB Clerk", attn: "Attn: VAB Clerk", street: "101 E James Lee Blvd", city: "Crestview", state: "FL", zip: "32536", confidence: "confirmed", sourceUrl: "https://okaloosaclerk.com/board-services/value-adjustment-board/" },
  "Okeechobee": { vabName: "Okeechobee County Clerk of Circuit Court and Comptroller – Clerk to the Board", attn: "Clerk to the Board, Room 222", street: "304 NW 2nd Street, Room 222", city: "Okeechobee", state: "FL", zip: "34972", confidence: "confirmed", sourceUrl: "https://myokeeclerk.com/vab" },
  "Orange": { vabName: "Orange County Comptroller – Orange County Value Adjustment Board", attn: "Orange County Value Adjustment Board", street: "P.O. Box 38", city: "Orlando", state: "FL", zip: "32802-0038", confidence: "confirmed", sourceUrl: "https://www.occompt.com/199/Value-Adjustment-Board", note: "VAB clerk is the COMPTROLLER, not the Clerk of Court." },
  "Osceola": { vabName: "Osceola Clerk of the Circuit Court & County Comptroller – VAB Clerk", attn: "Attn: VAB Clerk", street: "2 Courthouse Square, Office 2707", city: "Kissimmee", state: "FL", zip: "34741", confidence: "confirmed", sourceUrl: "https://osceolaclerk.com/value-adjustment-board/" },
  "Palm Beach": { vabName: "Palm Beach County Value Adjustment Board", attn: "Palm Beach County Value Adjustment Board", street: "P.O. Box 4036", city: "West Palm Beach", state: "FL", zip: "33402", confidence: "confirmed", sourceUrl: "https://www.mypalmbeachclerk.com/departments/value-adjustment-board-vab/petition-filing", note: "Hand delivery: 301 North Olive Ave, Room 206, West Palm Beach, FL 33401" },
  "Pasco": { vabName: "Pasco County Clerk & Comptroller – Value Adjustment Board, c/o Board Records Division", attn: "Value Adjustment Board, c/o Board Records Division", street: "14236 6th Street, Suite 201", city: "Dade City", state: "FL", zip: "33523", confidence: "confirmed", sourceUrl: "https://www.pascoclerk.com/307/Value-Adjustment-Board", note: "POSTMARK NOT SUFFICIENT — Pasco states postmarked petitions are untimely." },
  "Pinellas": { vabName: "Pinellas County Value Adjustment Board, c/o Clerk of the Circuit Court – Board Records", attn: "Pinellas County Value Adjustment Board, c/o Board Records Department", street: "315 Court Street, Fifth Floor", city: "Clearwater", state: "FL", zip: "33756", confidence: "confirmed", sourceUrl: "https://vabpetitions.mypinellasclerk.gov/" },
  "Polk": { vabName: "Polk County Value Adjustment Board", attn: "Attn: Comptroller VAB Clerk", street: "P.O. Box 988", city: "Bartow", state: "FL", zip: "33831", confidence: "confirmed", sourceUrl: "https://www.polkclerkfl.gov/196/Value-Adjustment-Board" },
  "Putnam": { vabName: "Putnam County Clerk of the Circuit Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 758", city: "Palatka", state: "FL", zip: "32178", confidence: "confirmed", sourceUrl: "https://putnamclerk.com/county-comptroller/value-adjustment-board/" },
  "St. Johns": { vabName: "St. Johns County Clerk of the Circuit Court and County Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "4010 Lewis Speedway", city: "St. Augustine", state: "FL", zip: "32084", confidence: "confirmed", sourceUrl: "https://stjohnsclerk.com/" },
  "St. Lucie": { vabName: "St. Lucie County Clerk of the Circuit Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "2300 Virginia Avenue", city: "Fort Pierce", state: "FL", zip: "34982", confidence: "confirmed", sourceUrl: "https://stlucieclerk.gov/services/value-adjustment-board" },
  "Santa Rosa": { vabName: "Santa Rosa County Clerk of Court & Comptroller – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "6495 Caroline St., Suite A", city: "Milton", state: "FL", zip: "32570", confidence: "confirmed", sourceUrl: "https://santarosaclerk.com/other-services/value-adjustment-board-public-notice/" },
  "Sarasota": { vabName: "Sarasota Clerk of the Circuit Court and County Comptroller – Clerk to the Value Adjustment Board", attn: "Attn: VAB Clerk", street: "P.O. Box 3079", city: "Sarasota", state: "FL", zip: "34230-3079", confidence: "unconfirmed", sourceUrl: "https://www.sarasotaclerk.com/Home-and-Property/Value-Adjustment-Board", note: "2026-08-03: the Clerk's own VAB page corroborates P.O. Box 3079, Sarasota FL 34230-3079, and states the fee is $50. That is now two official sources for the PO Box against one each for the street addresses. Remaining question is the check payee only — phone (941) 861-7400." },
  "Seminole": { vabName: "Seminole County Clerk of the Circuit Court & Comptroller – VAB Office", attn: "Attn: Clerk's Administration – Value Adjustment Board", street: "91 Eslinger Way", city: "Sanford", state: "FL", zip: "32773", confidence: "confirmed", sourceUrl: "https://www.seminoleclerk.org/value-adjustment-board/" },
  "Sumter": { vabName: "Sumter County Value Adjustment Board, c/o Clerk of the Circuit Court", attn: "Value Adjustment Board, c/o Clerk of the Circuit Court", street: "P.O. Box 247", city: "Bushnell", state: "FL", zip: "33513", confidence: "confirmed", sourceUrl: "https://www.sumterclerk.com/value-adjustment-board" },
  "Suwannee": { vabName: "Suwannee County Clerk of the Circuit Court – Clerk of the Value Adjustment Board", attn: "Attn: Clerk of the Value Adjustment Board", street: "200 South Ohio Avenue", city: "Live Oak", state: "FL", zip: "32064", confidence: "confirmed", sourceUrl: "https://www.suwgov.org/county-comptroller/value-adjustment-board/" },
  "Taylor": { vabName: "Taylor County Clerk of the Circuit Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "108 North Jefferson Street, Suite 102", city: "Perry", state: "FL", zip: "32347", confidence: "confirmed", sourceUrl: "https://taylorclerk.com/departments/value-adjustment-board/" },
  "Union": { vabName: "Union County Clerk of Courts & Comptroller – Clerk to the Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "55 West Main Street, Room 103", city: "Lake Butler", state: "FL", zip: "32054", confidence: "unconfirmed", sourceUrl: "https://unionclerk.com/value-adjustment-board/", note: "No dedicated petition mailing address published. Confirm by phone." },
  "Volusia": { vabName: "Volusia County Value Adjustment Board", attn: "Value Adjustment Board", street: "123 W. Indiana Ave., Suite 301", city: "DeLand", state: "FL", zip: "32720", confidence: "unconfirmed", sourceUrl: "https://www.volusia.org/government/county-council/advisory-boards/value-adjustment-board.stml", note: "2026-08-03: volusia.org VAB page re-verified as Suite 301 — the brochure saying 304 appears to be stale. Remaining question is the check payee only — phone (386) 740-5164, valueadjustmentboard@volusia.gov." },
  "Wakulla": { vabName: "Wakulla County Clerk of Circuit Court & Comptroller – Clerk of the Value Adjustment Board", attn: "Clerk of the Value Adjustment Board", street: "3056 Crawfordville Highway, Room 129", city: "Crawfordville", state: "FL", zip: "32327", confidence: "confirmed", sourceUrl: "https://wakullaclerk.org/clerk_to_the_board/value_adjustment_board.php" },
  "Walton": { vabName: "Walton County Clerk of Courts & Comptroller – VAB Clerk", attn: "Attn: VAB Clerk", street: "571 US Highway 90 East", city: "DeFuniak Springs", state: "FL", zip: "32433", confidence: "unconfirmed", sourceUrl: "https://waltonpa.com/general-information/appeals-process/", note: "Property Appraiser site lists P.O. Box 1260, DeFuniak Springs, FL 32435 for petitions; not corroborated on the Clerk's own site. Confirm by phone." },
  "Washington": { vabName: "Washington County Clerk of Court – Value Adjustment Board", attn: "Attn: Value Adjustment Board", street: "P.O. Box 647", city: "Chipley", state: "FL", zip: "32428", confidence: "confirmed", sourceUrl: "https://www.washingtonclerk.com/additional-informationuseful-links/value-adjustment-board/", note: "Physical: 1293 Jackson Avenue, Suite 101, Chipley, FL 32428" },
};

/** Normalize a county name to the table's key format. */
function normalizeCounty(countyName) {
  if (!countyName) return '';
  let c = String(countyName).replace(/\s+County$/i, '').trim();
  // Common variants returned by geocoders and LLM fallbacks.
  const aliases = {
    'saint johns': 'St. Johns', 'st johns': 'St. Johns', 'st. johns': 'St. Johns',
    'saint lucie': 'St. Lucie', 'st lucie': 'St. Lucie', 'st. lucie': 'St. Lucie',
    'miami dade': 'Miami-Dade', 'miami-dade': 'Miami-Dade', 'miamidade': 'Miami-Dade', 'dade': 'Miami-Dade',
    'desoto': 'DeSoto', 'de soto': 'DeSoto',
    'indian river': 'Indian River', 'palm beach': 'Palm Beach', 'santa rosa': 'Santa Rosa',
  };
  const key = c.toLowerCase();
  if (aliases[key]) return aliases[key];
  // Title-case fallback so "ORANGE" and "orange" both resolve.
  // Title-case each ALPHA RUN, not each whitespace-delimited token. `\w\S*`
  // swallowed the hyphen, so "Miami-Dade" normalized to "Miami-dade" — which
  // matched no key in either table, so getFlVabAddress returned null and Florida's
  // LARGEST county was hard-blocked at checkout as "not verified".
  return c.replace(/[A-Za-z]+/g, (t) => t.charAt(0).toUpperCase() + t.slice(1).toLowerCase());
}

/**
 * Get the VAB Clerk mailing address for a Florida county.
 * Returns null if the county is unknown OR unconfirmed — callers MUST treat
 * null as "cannot file" and must never substitute another address.
 */
export function getFlVabAddress(countyName) {
  const entry = FL_VAB_ADDRESSES[normalizeCounty(countyName)];
  if (!entry) return null;
  if (entry.confidence !== 'confirmed') return null;
  return entry;
}

/** Raw lookup including unconfirmed entries — for admin/ops tooling only. */
export function getFlVabAddressRaw(countyName) {
  return FL_VAB_ADDRESSES[normalizeCounty(countyName)] || null;
}

/** True only if we can safely mail a petition for this county today. */
export function isFlCountySupported(countyName) {
  return getFlVabAddress(countyName) !== null;
}

/** True if this county requires physical receipt (postmark not sufficient). */
export function flCountyRequiresReceipt(countyName) {
  return FL_POSTMARK_NOT_ACCEPTED.includes(normalizeCounty(countyName));
}

/** Counties currently blocked pending phone verification. */
/**
 * All 67 Florida county names, sorted. Used to populate the county picker in the
 * apply funnel so a customer can correct or supply their county when the Census
 * geocoder cannot place the address — a DROPDOWN, never free text, because a
 * typo here mails the petition and the fee cheque to the wrong government office.
 */
export const FL_COUNTY_NAMES = Object.keys(FL_VAB_ADDRESSES).sort((a, b) => a.localeCompare(b));

export function getUnconfirmedFlCounties() {
  return Object.entries(FL_VAB_ADDRESSES)
    .filter(([, v]) => v.confidence !== 'confirmed')
    .map(([k]) => k);
}

export default FL_VAB_ADDRESSES;
