// lib/georgiaSuburbs.js
// Georgia neighborhood/suburb pages data
// Used by pages/georgia/[city].js dynamic route

export const georgiaSuburbs = [

  // FULTON COUNTY / NORTH FULTON
  { slug: "alpharetta-ga", name: "Alpharetta", county: "Fulton", countySlug: "fulton-county-ga", district: "Fulton County Board of Assessors", districtUrl: "https://www.fultonassessor.org", metro: "Atlanta", medianValue: 640000, avgSavings: 2100, pop: "high", description: "Alpharetta is one of North Atlanta's premier tech-corridor suburbs with some of Georgia's highest home values. The Fulton County Board of Assessors frequently over-values Alpharetta's premium neighborhoods including Avalon, Manning Gate, and Windward." },
  { slug: "sandy-springs-ga", name: "Sandy Springs", county: "Fulton", countySlug: "fulton-county-ga", district: "Fulton County Board of Assessors", districtUrl: "https://www.fultonassessor.org", metro: "Atlanta", medianValue: 590000, avgSavings: 1950, pop: "high", description: "Sandy Springs hugs the Chattahoochee River just north of Atlanta with some of Fulton County's most valuable estate homes. Mass-appraisal models struggle with Sandy Springs' diverse mix of gated communities, river estates, and high-rise condos." },
  { slug: "roswell-ga", name: "Roswell", county: "Fulton", countySlug: "fulton-county-ga", district: "Fulton County Board of Assessors", districtUrl: "https://www.fultonassessor.org", metro: "Atlanta", medianValue: 520000, avgSavings: 1720, pop: "high", description: "Roswell combines historic charm with upscale new construction along the Chattahoochee corridor. Fulton County assessments frequently miss lot premiums and neighborhood-level variation that drive significant value differences." },
  { slug: "johns-creek-ga", name: "Johns Creek", county: "Fulton", countySlug: "fulton-county-ga", district: "Fulton County Board of Assessors", districtUrl: "https://www.fultonassessor.org", metro: "Atlanta", medianValue: 570000, avgSavings: 1880, pop: "high", description: "Johns Creek ranks among Georgia's wealthiest cities, with master-planned communities anchored by top-rated schools. Fulton County's approach often fails to capture nuanced value differences between gated and non-gated communities." },
  { slug: "milton-ga", name: "Milton", county: "Fulton", countySlug: "fulton-county-ga", district: "Fulton County Board of Assessors", districtUrl: "https://www.fultonassessor.org", metro: "Atlanta", medianValue: 750000, avgSavings: 2450, pop: "high", description: "Milton is Fulton County's equestrian enclave with large-lot estates, horse farms, and luxury custom homes that are notoriously difficult to value accurately. Sparse comparable sales make Milton one of Georgia's highest-upside appeal markets." },

  // COBB COUNTY
  { slug: "marietta-ga", name: "Marietta", county: "Cobb", countySlug: "cobb-county-ga", district: "Cobb County Board of Tax Assessors", districtUrl: "https://www.cobbtax.org", metro: "Atlanta", medianValue: 420000, avgSavings: 1390, pop: "high", description: "Marietta is Cobb County's seat and one of Atlanta's largest suburb cities. Cobb County's mass-appraisal models often over-value Marietta's highly varied neighborhoods from established bungalows to newer subdivisions near Cumberland." },
  { slug: "smyrna-ga", name: "Smyrna", county: "Cobb", countySlug: "cobb-county-ga", district: "Cobb County Board of Tax Assessors", districtUrl: "https://www.cobbtax.org", metro: "Atlanta", medianValue: 410000, avgSavings: 1360, pop: "high", description: "Smyrna's explosive growth along the Cumberland and Vinings corridors has created rapid price appreciation and assessments that frequently lag real-time market corrections." },
  { slug: "kennesaw-ga", name: "Kennesaw", county: "Cobb", countySlug: "cobb-county-ga", district: "Cobb County Board of Tax Assessors", districtUrl: "https://www.cobbtax.org", metro: "Atlanta", medianValue: 370000, avgSavings: 1230, pop: "high", description: "Kennesaw is anchored by Kennesaw State University and strong I-75 corridor access. High volumes of new construction make Cobb County mass-appraisal particularly error-prone in Kennesaw." },
  { slug: "acworth-ga", name: "Acworth", county: "Cobb", countySlug: "cobb-county-ga", district: "Cobb County Board of Tax Assessors", districtUrl: "https://www.cobbtax.org", metro: "Atlanta", medianValue: 350000, avgSavings: 1160, pop: "medium", description: "Acworth sits on Lake Acworth and Lake Allatoona with lakefront properties that are especially difficult to value accurately. Cobb County assessors apply broad averages that often miss waterfront premiums and dock access." },
  { slug: "powder-springs-ga", name: "Powder Springs", county: "Cobb", countySlug: "cobb-county-ga", district: "Cobb County Board of Tax Assessors", districtUrl: "https://www.cobbtax.org", metro: "Atlanta", medianValue: 320000, avgSavings: 1060, pop: "medium", description: "Powder Springs has seen significant residential growth as buyers seek affordable alternatives in western Cobb County. New construction and resale competition has softened values that Cobb County assessments may not fully reflect." },

  // GWINNETT COUNTY
  { slug: "duluth-ga", name: "Duluth", county: "Gwinnett", countySlug: "gwinnett-county-ga", district: "Gwinnett County Board of Tax Assessors", districtUrl: "https://www.gwinnettassessor.com", metro: "Atlanta", medianValue: 440000, avgSavings: 1460, pop: "high", description: "Duluth is one of Gwinnett County's most desirable communities with top-rated schools and a growing business corridor. Gwinnett County's model frequently over-values Duluth's premium subdivisions relative to actual market transactions." },
  { slug: "suwanee-ga", name: "Suwanee", county: "Gwinnett", countySlug: "gwinnett-county-ga", district: "Gwinnett County Board of Tax Assessors", districtUrl: "https://www.gwinnettassessor.com", metro: "Atlanta", medianValue: 490000, avgSavings: 1620, pop: "high", description: "Suwanee consistently earns national recognition as one of America's best places to live, driving strong demand and high home values. That demand also drives aggressive Gwinnett County assessments that frequently outpace actual closing prices." },
  { slug: "lawrenceville-ga", name: "Lawrenceville", county: "Gwinnett", countySlug: "gwinnett-county-ga", district: "Gwinnett County Board of Tax Assessors", districtUrl: "https://www.gwinnettassessor.com", metro: "Atlanta", medianValue: 350000, avgSavings: 1160, pop: "high", description: "Lawrenceville is Gwinnett County's seat and one of Atlanta's largest suburban cities. With hundreds of thousands of parcels to value, Gwinnett's models are particularly prone to error in Lawrenceville's highly varied neighborhoods." },
  { slug: "buford-ga", name: "Buford", county: "Gwinnett", countySlug: "gwinnett-county-ga", district: "Gwinnett County Board of Tax Assessors", districtUrl: "https://www.gwinnettassessor.com", metro: "Atlanta", medianValue: 420000, avgSavings: 1390, pop: "medium", description: "Buford is home to the Mall of Georgia and some of Gwinnett County's most desirable new construction communities along the I-985 corridor. Rapid development and shifting market conditions make Buford a strong appeal market." },
  { slug: "peachtree-corners-ga", name: "Peachtree Corners", county: "Gwinnett", countySlug: "gwinnett-county-ga", district: "Gwinnett County Board of Tax Assessors", districtUrl: "https://www.gwinnettassessor.com", metro: "Atlanta", medianValue: 460000, avgSavings: 1520, pop: "high", description: "Peachtree Corners is Gwinnett County's technology hub, home to Technology Park Atlanta and established neighborhoods with high property values. The commercial and residential mix creates valuation complexity that mass-appraisal models often handle imprecisely." },
  { slug: "norcross-ga", name: "Norcross", county: "Gwinnett", countySlug: "gwinnett-county-ga", district: "Gwinnett County Board of Tax Assessors", districtUrl: "https://www.gwinnettassessor.com", metro: "Atlanta", medianValue: 340000, avgSavings: 1130, pop: "medium", description: "Norcross is one of Gwinnett County's most diverse communities with a historic downtown and a wide range of housing types. Valuation inconsistency across Norcross's diverse housing stock creates frequent over-assessment opportunities." },

  // CHEROKEE COUNTY
  { slug: "canton-ga", name: "Canton", county: "Cherokee", countySlug: "cherokee-county-ga", district: "Cherokee County Board of Tax Assessors", districtUrl: "https://www.cherokeecountyga.gov/tax-assessors", metro: "Atlanta", medianValue: 390000, avgSavings: 1290, pop: "high", description: "Canton is Cherokee County's seat and fastest-growing city, drawing Atlanta families seeking larger lots and lower density. Cherokee County's rapid growth has created a challenging appraisal environment where new construction comps are sparse." },
  { slug: "woodstock-ga", name: "Woodstock", county: "Cherokee", countySlug: "cherokee-county-ga", district: "Cherokee County Board of Tax Assessors", districtUrl: "https://www.cherokeecountyga.gov/tax-assessors", metro: "Atlanta", medianValue: 420000, avgSavings: 1390, pop: "high", description: "Woodstock has transformed into one of Atlanta's most desirable suburbs with a vibrant downtown and top-rated schools. Cherokee County assessments frequently lag market corrections in the city's newer master-planned communities." },
  { slug: "ball-ground-ga", name: "Ball Ground", county: "Cherokee", countySlug: "cherokee-county-ga", district: "Cherokee County Board of Tax Assessors", districtUrl: "https://www.cherokeecountyga.gov/tax-assessors", metro: "Atlanta", medianValue: 360000, avgSavings: 1190, pop: "medium", description: "Ball Ground is Cherokee County's fastest-growing smaller city with new subdivisions replacing agricultural land. The sparse comparable sales environment makes mass-appraisal particularly error-prone here." },

  // FORSYTH COUNTY
  { slug: "cumming-ga", name: "Cumming", county: "Forsyth", countySlug: "forsyth-county-ga", district: "Forsyth County Board of Tax Assessors", districtUrl: "https://www.forsythco.com/departments-offices/board-of-assessors", metro: "Atlanta", medianValue: 500000, avgSavings: 1660, pop: "high", description: "Cumming is Forsyth County's seat and one of the fastest-growing cities in the United States, anchored by Lake Lanier access and top-rated schools. Forsyth County's explosive growth has created consistent over-assessment opportunities." },
  { slug: "sugar-hill-ga", name: "Sugar Hill", county: "Forsyth", countySlug: "forsyth-county-ga", district: "Forsyth County Board of Tax Assessors", districtUrl: "https://www.forsythco.com/departments-offices/board-of-assessors", metro: "Atlanta", medianValue: 440000, avgSavings: 1460, pop: "high", description: "Sugar Hill straddles the Forsyth-Gwinnett county line with strong schools, active parks, and suburban neighborhoods. Assessment inconsistencies between similarly-valued homes are common in Sugar Hill's diverse housing stock." },

  // HALL COUNTY
  { slug: "gainesville-ga", name: "Gainesville", county: "Hall", countySlug: "hall-county-ga", district: "Hall County Board of Tax Assessors", districtUrl: "https://www.hallcounty.org/189/Tax-Assessors", metro: "Atlanta", medianValue: 370000, avgSavings: 1230, pop: "high", description: "Gainesville is Hall County's largest city anchored by Lake Lanier's southern shores. Hall County assessments frequently struggle with lakefront properties where view quality, dock access, and lot depth create major value differentials." },
  { slug: "braselton-ga", name: "Braselton", county: "Hall", countySlug: "hall-county-ga", district: "Hall County Board of Tax Assessors", districtUrl: "https://www.hallcounty.org/189/Tax-Assessors", metro: "Atlanta", medianValue: 410000, avgSavings: 1360, pop: "medium", description: "Braselton is home to Chateau Elan winery resort and upscale master-planned communities. Sparse comparable sales in this premium resort community create assessment inaccuracies that favor homeowners who appeal." },

  // DEKALB COUNTY
  { slug: "decatur-ga", name: "Decatur", county: "DeKalb", countySlug: "dekalb-county-ga", district: "DeKalb County Board of Tax Assessors", districtUrl: "https://www.dekalbcountyga.gov/tax-assessor", metro: "Atlanta", medianValue: 510000, avgSavings: 1690, pop: "high", description: "Decatur is one of Atlanta's most walkable suburbs with a nationally recognized school system. DeKalb County assessments often miss the neighborhood-level micro-market dynamics that drive significant price premiums on Decatur's most coveted streets." },
  { slug: "tucker-ga", name: "Tucker", county: "DeKalb", countySlug: "dekalb-county-ga", district: "DeKalb County Board of Tax Assessors", districtUrl: "https://www.dekalbcountyga.gov/tax-assessor", metro: "Atlanta", medianValue: 390000, avgSavings: 1290, pop: "medium", description: "Tucker is a rapidly evolving DeKalb County community with a mix of established neighborhoods and transitional blocks. DeKalb's models often over-value Tucker homes by grouping them with higher-demand neighborhoods." },
  { slug: "dunwoody-ga", name: "Dunwoody", county: "DeKalb", countySlug: "dekalb-county-ga", district: "DeKalb County Board of Tax Assessors", districtUrl: "https://www.dekalbcountyga.gov/tax-assessor", metro: "Atlanta", medianValue: 510000, avgSavings: 1690, pop: "high", description: "Dunwoody is DeKalb County's most affluent city with high-demand neighborhoods near Perimeter Center and strong school ratings. DeKalb assessors frequently apply county-wide appreciation trends that do not reflect Dunwoody's specific market dynamics." },
  { slug: "brookhaven-ga", name: "Brookhaven", county: "DeKalb", countySlug: "dekalb-county-ga", district: "DeKalb County Board of Tax Assessors", districtUrl: "https://www.dekalbcountyga.gov/tax-assessor", metro: "Atlanta", medianValue: 560000, avgSavings: 1850, pop: "high", description: "Brookhaven is one of Atlanta's fastest-appreciating close-in suburbs with luxury new construction replacing older ranch homes. DeKalb assessments in Brookhaven often miss condition and renovation premiums that drive significant price variation." },
  { slug: "stone-mountain-ga", name: "Stone Mountain", county: "DeKalb", countySlug: "dekalb-county-ga", district: "DeKalb County Board of Tax Assessors", districtUrl: "https://www.dekalbcountyga.gov/tax-assessor", metro: "Atlanta", medianValue: 280000, avgSavings: 930, pop: "medium", description: "Stone Mountain sits at the base of Georgia's iconic granite monolith. DeKalb's models frequently over-value Stone Mountain properties by applying area-wide appreciation trends to neighborhoods with slower actual appreciation." },

  // HENRY COUNTY
  { slug: "mcdonough-ga", name: "McDonough", county: "Henry", countySlug: "henry-county-ga", district: "Henry County Board of Tax Assessors", districtUrl: "https://www.co.henry.ga.us/departments/tax-assessors", metro: "Atlanta", medianValue: 330000, avgSavings: 1090, pop: "high", description: "McDonough is Henry County's seat and one of Atlanta's southside growth stories, drawing buyers priced out of Fulton and Clayton counties. Henry County's rapid expansion has created appraisal challenges where new construction comps and resale softening are not fully captured." },
  { slug: "stockbridge-ga", name: "Stockbridge", county: "Henry", countySlug: "henry-county-ga", district: "Henry County Board of Tax Assessors", districtUrl: "https://www.co.henry.ga.us/departments/tax-assessors", metro: "Atlanta", medianValue: 310000, avgSavings: 1030, pop: "medium", description: "Stockbridge is one of Henry County's most established communities with a range of housing types from townhomes to larger single-family homes. Henry County assessments often apply county-wide averages that do not account for neighborhood-level variation." },
  { slug: "locust-grove-ga", name: "Locust Grove", county: "Henry", countySlug: "henry-county-ga", district: "Henry County Board of Tax Assessors", districtUrl: "https://www.co.henry.ga.us/departments/tax-assessors", metro: "Atlanta", medianValue: 295000, avgSavings: 980, pop: "medium", description: "Locust Grove is one of Henry County's fastest-growing communities with new master-planned subdivisions and strong I-75 corridor access. Rapid new construction creates appraisal challenges where models struggle to distinguish new and resale sales." },

  // PAULDING / DOUGLAS / FAYETTE
  { slug: "dallas-ga", name: "Dallas", county: "Paulding", countySlug: "paulding-county-ga", district: "Paulding County Board of Tax Assessors", districtUrl: "https://www.paulding.gov/186/Tax-Assessors-Office", metro: "Atlanta", medianValue: 310000, avgSavings: 1030, pop: "medium", description: "Dallas is Paulding County's seat drawing buyers seeking large lots and lower density. Paulding County's fast growth and sparse comparable sales data in newer subdivisions create consistent appraisal inaccuracies." },
  { slug: "douglasville-ga", name: "Douglasville", county: "Douglas", countySlug: "douglas-county-ga", district: "Douglas County Board of Tax Assessors", districtUrl: "https://celebratedouglas.com/departments/tax-assessors/", metro: "Atlanta", medianValue: 295000, avgSavings: 980, pop: "high", description: "Douglasville is Douglas County's largest city and a key western Atlanta suburb with strong I-20 corridor access. Douglas County homeowners frequently find assessments that exceed what comparable homes are actually trading for." },
  { slug: "peachtree-city-ga", name: "Peachtree City", county: "Fayette", countySlug: "fayette-county-ga", district: "Fayette County Board of Tax Assessors", districtUrl: "https://www.fayettecountyga.gov/tax_assessors", metro: "Atlanta", medianValue: 500000, avgSavings: 1660, pop: "high", description: "Peachtree City is one of Georgia's most unique planned communities with over 90 miles of cart paths. Fayette County assessors face significant challenges valuing Peachtree City's diverse property types accurately." },

  // COWETA COUNTY
  { slug: "newnan-ga", name: "Newnan", county: "Coweta", countySlug: "coweta-county-ga", district: "Coweta County Board of Tax Assessors", districtUrl: "https://www.coweta.ga.us/government/departments/tax-assessors", metro: "Atlanta", medianValue: 370000, avgSavings: 1230, pop: "high", description: "Newnan is Coweta County's historic county seat and one of southwest Atlanta's fastest-growing communities. Coweta County has absorbed significant Atlanta overflow, creating appraisal challenges where newer subdivisions' shifting values are not accurately reflected." },
  { slug: "sharpsburg-ga", name: "Sharpsburg", county: "Coweta", countySlug: "coweta-county-ga", district: "Coweta County Board of Tax Assessors", districtUrl: "https://www.coweta.ga.us/government/departments/tax-assessors", metro: "Atlanta", medianValue: 420000, avgSavings: 1390, pop: "medium", description: "Sharpsburg is one of Coweta County's most sought-after communities for large-lot estate homes and equestrian properties. Sparse comparable sales data for larger acreage properties makes mass-appraisal accuracy particularly challenging." },

  // SAVANNAH / COASTAL
  { slug: "savannah-ga", name: "Savannah", county: "Chatham", countySlug: "chatham-county-ga", district: "Chatham County Board of Tax Assessors", districtUrl: "https://www.chathamcounty.org/Government/Departments/Board-of-Assessors", metro: "Savannah", medianValue: 330000, avgSavings: 1090, pop: "high", description: "Savannah is Georgia's second-largest city with a historic district that commands significant real estate premiums. Chatham County assessments often miss the nuanced value differences between Savannah's highly varied historic and suburban neighborhoods." },
  { slug: "pooler-ga", name: "Pooler", county: "Chatham", countySlug: "chatham-county-ga", district: "Chatham County Board of Tax Assessors", districtUrl: "https://www.chathamcounty.org/Government/Departments/Board-of-Assessors", metro: "Savannah", medianValue: 310000, avgSavings: 1030, pop: "high", description: "Pooler is one of Georgia's fastest-growing cities near Savannah/Hilton Head International Airport. Rapid new construction in Pooler creates appraisal challenges that frequently result in over-assessment." },
  { slug: "richmond-hill-ga", name: "Richmond Hill", county: "Bryan", countySlug: "bryan-county-ga", district: "Bryan County Board of Tax Assessors", districtUrl: "https://www.bryancountyga.org/government/boards/board-of-tax-assessors", metro: "Savannah", medianValue: 360000, avgSavings: 1190, pop: "medium", description: "Richmond Hill is Bryan County's largest city and a growing Savannah suburb known for strong schools and family-friendly neighborhoods. Bryan County's rapid growth from Savannah overflow creates appraisal inconsistencies in newer subdivisions." },
  { slug: "st-simons-island-ga", name: "St. Simons Island", county: "Glynn", countySlug: "glynn-county-ga", district: "Glynn County Board of Tax Assessors", districtUrl: "https://www.glynncounty.org/182/Tax-Assessors", metro: "Brunswick", medianValue: 480000, avgSavings: 1590, pop: "medium", description: "St. Simons Island and the Golden Isles carry some of Georgia's highest coastal property values. Glynn County assessments frequently struggle with the wide variance in value driven by waterfront access, view quality, and beach proximity." },

  // AUGUSTA / COLUMBIA COUNTY
  { slug: "evans-ga", name: "Evans", county: "Columbia", countySlug: "columbia-county-ga", district: "Columbia County Board of Tax Assessors", districtUrl: "https://www.columbiacountyga.gov", metro: "Augusta", medianValue: 340000, avgSavings: 1130, pop: "high", description: "Evans is one of Columbia County's most established suburban communities with top-rated schools and a growing medical corridor. Columbia County homeowners frequently find that mass-appraisal models apply area-wide appreciation averages that exceed what individual properties are actually worth." },
  { slug: "grovetown-ga", name: "Grovetown", county: "Columbia", countySlug: "columbia-county-ga", district: "Columbia County Board of Tax Assessors", districtUrl: "https://www.columbiacountyga.gov", metro: "Augusta", medianValue: 290000, avgSavings: 960, pop: "high", description: "Grovetown is one of Columbia County's fastest-growing communities with new subdivisions drawing Fort Gordon/Cyber Command personnel and Augusta-area families. Rapid growth creates assessment inaccuracies in Grovetown's expanding neighborhoods." },
  { slug: "martinez-ga", name: "Martinez", county: "Columbia", countySlug: "columbia-county-ga", district: "Columbia County Board of Tax Assessors", districtUrl: "https://www.columbiacountyga.gov", metro: "Augusta", medianValue: 270000, avgSavings: 900, pop: "medium", description: "Martinez is an unincorporated Columbia County community that has grown significantly as Augusta's western suburbs expanded. Assessment inconsistencies between older and newer neighborhoods create regular appeal opportunities." },

  // COLUMBUS / MUSCOGEE
  { slug: "columbus-ga", name: "Columbus", county: "Muscogee", countySlug: "muscogee-county-ga", district: "Muscogee County Board of Tax Assessors", districtUrl: "https://www.columbusga.gov/assessment/default.htm", metro: "Columbus", medianValue: 195000, avgSavings: 650, pop: "high", description: "Columbus is Georgia's second-largest city and Muscogee County's urban core. Muscogee County assessments frequently over-value properties in established Columbus neighborhoods relative to what homes are actually trading for." },
  { slug: "fortson-ga", name: "Fortson", county: "Harris", countySlug: "harris-county-ga", district: "Harris County Board of Tax Assessors", districtUrl: "https://www.harriscountyga.gov/departments/tax-assessors/", metro: "Columbus", medianValue: 310000, avgSavings: 1030, pop: "medium", description: "Fortson is one of Harris County's premier suburban communities just north of Columbus with large-lot estates and newer subdivisions. Harris County assessments in Fortson often miss the condition and lot-quality differentials that drive major value variation." },

  // MACON / BIBB
  { slug: "macon-ga", name: "Macon", county: "Bibb", countySlug: "bibb-county-ga", district: "Bibb County Board of Tax Assessors", districtUrl: "https://www.maconbibb.us/tax-assessors/", metro: "Macon", medianValue: 185000, avgSavings: 610, pop: "high", description: "Macon is Middle Georgia's largest city with a diverse mix of historic neighborhoods, suburban developments, and rural character. Bibb County assessments across Macon's varied housing stock create consistent opportunities for homeowners who challenge inflated valuations." },
  { slug: "warner-robins-ga", name: "Warner Robins", county: "Houston", countySlug: "houston-county-ga", district: "Houston County Board of Tax Assessors", districtUrl: "https://www.houstoncountyga.org/government/departments/tax-assessors", metro: "Macon", medianValue: 220000, avgSavings: 730, pop: "high", description: "Warner Robins is Houston County's largest city anchored by Robins Air Force Base and a growing civilian economy. Houston County assessments frequently apply county-wide appreciation averages to neighborhoods with highly varied actual market performance." },
  { slug: "kathleen-ga", name: "Kathleen", county: "Houston", countySlug: "houston-county-ga", district: "Houston County Board of Tax Assessors", districtUrl: "https://www.houstoncountyga.org/government/departments/tax-assessors", metro: "Macon", medianValue: 260000, avgSavings: 860, pop: "medium", description: "Kathleen is one of Houston County's fastest-growing communities with suburban neighborhoods drawing families south of Warner Robins. Rapid new construction creates the same appraisal inaccuracies seen across other high-growth Georgia communities." },

  // NORTH GEORGIA
  { slug: "flowery-branch-ga", name: "Flowery Branch", county: "Hall", countySlug: "hall-county-ga", district: "Hall County Board of Tax Assessors", districtUrl: "https://www.hallcounty.org/189/Tax-Assessors", metro: "Atlanta", medianValue: 380000, avgSavings: 1260, pop: "medium", description: "Flowery Branch sits on the southeastern shore of Lake Lanier with a mix of lakefront estates and newer suburban subdivisions. Hall County assessments struggle with the wide value range created by Lake Lanier access versus inland location." },
  { slug: "dawsonville-ga", name: "Dawsonville", county: "Dawson", countySlug: "dawson-county-ga", district: "Dawson County Board of Tax Assessors", districtUrl: "https://www.dawsoncounty.org/departments/tax_assessors/index.php", metro: "Atlanta", medianValue: 360000, avgSavings: 1190, pop: "medium", description: "Dawsonville is Dawson County's seat and one of North Georgia's fastest-growing communities with mountain views and Lake Lanier access. Dawson County's rapid growth creates appraisal challenges where models frequently over-value properties." },
  { slug: "jasper-ga", name: "Jasper", county: "Pickens", countySlug: "pickens-county-ga", district: "Pickens County Board of Tax Assessors", districtUrl: "https://www.pickenscountyga.gov", metro: "Atlanta", medianValue: 340000, avgSavings: 1130, pop: "medium", description: "Jasper is the gateway to the North Georgia mountains drawing retirees and Atlanta remote-workers with mountain views and lower density. Pickens County's assessment of mountain-view properties frequently misses the significant premium that specific views command." },

  // ROME / FLOYD COUNTY
  { slug: "rome-ga", name: "Rome", county: "Floyd", countySlug: "floyd-county-ga", district: "Floyd County Board of Tax Assessors", districtUrl: "https://www.floydcountyga.gov/tax-assessors", metro: "Rome", medianValue: 220000, avgSavings: 730, pop: "high", description: "Rome is Floyd County's largest city and northwest Georgia's urban center with a diverse real estate market ranging from historic downtown homes to rural acreage. Floyd County assessments across Rome's varied neighborhoods create regular appeal opportunities." },

];

export function getGaSuburbBySlug(slug) {
  return georgiaSuburbs.find(c => c.slug === slug) || null;
}

export function getAllGaSuburbSlugs() {
  return georgiaSuburbs.map(c => ({ params: { city: c.slug } }));
}
