import Head from 'next/head';
import { useState } from 'react';
import { useRouter } from 'next/router';
const C = { navy:"#1B3A6B",gold:"#FFC940",darkNavy:"#0F1F3D",bg:"#F4F7FC",lightBlue:"#EEF3FB",bodyGray:"#5A6B82",mutedGray:"#8596AF",border:"#E8EDF4",white:"#FFFFFF",green:"#2E7D52" };
const FONT = "https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=DM+Sans:wght@400;500&display=swap";
const faqs = [
  ["What is the deadline to appeal Fayetteville property taxes?","The Washington County Board of Equalization deadline is the third Monday in August — August 17, 2026. Postmark by this date. TaxAppeal files via USPS certified mail."],
  ["How does Arkansas assess property taxes?","Arkansas assesses at 20% of fair market value. A home worth $295,000 has an assessed value of $59,000. You are appealing the market value — a 10% reduction means 10% less assessed value and tax."],
  ["How much can Fayetteville homeowners save?","Washington County homeowners who successfully appeal save an average of $740 per year. TaxAppeal charges $89 flat — you keep 100% of savings."],
  ["What is the Washington County Board of Equalization?","The Washington County Board of Equalization hears property tax appeals every August. Three members appointed by the county judge hear evidence and issue decisions."],
  ["Does postmark count in Arkansas?","Yes. Arkansas only requires your appeal be postmarked by the third Monday in August. TaxAppeal uses USPS certified mail for a documented postmark."],
  ["Can I appeal every year?","Yes. Arkansas homeowners can file a new Board of Equalization appeal every August."],
  ["Do I need to attend a hearing?","Your representative can attend. TaxAppeal files your written protest with evidence — many counties accept it without a personal appearance."],
];
export default function Fayetteville() {
  const router = useRouter();
  const [openFaq, setOpenFaq] = useState(null);
  const go = () => router.push('/apply');
  return (
    <>
      <Head>
        <title>Fayetteville Property Tax Appeal Service | File for $89 | TaxAppeal USA</title>
        <meta name="description" content="Appeal your Fayetteville property taxes for $89 flat. Washington County homeowners save an average of $740/year. We file with the Board of Equalization via certified mail before the August 17 deadline." />
        <link rel="canonical" href="https://www.taxappealusa.com/fayetteville" />
        <meta property="og:title" content="Fayetteville Property Tax Appeal — $89 Flat Fee | TaxAppeal USA" />
        <meta property="og:url" content="https://www.taxappealusa.com/fayetteville" />
        <meta property="og:type" content="website" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({"@context":"https://schema.org","@type":"FAQPage","mainEntity":faqs.map(([q,a])=>( {"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}}))})}} />
      </Head>
      <style>{`@import url('${FONT}');*{box-sizing:border-box;margin:0;padding:0;}body{font-family:'DM Sans',sans-serif;background:${C.bg};color:${C.darkNavy};}.btn{background:${C.navy};color:#fff;border:none;border-radius:8px;padding:16px 36px;font-size:16px;font-weight:500;cursor:pointer;}.btn:hover{background:${C.gold};color:${C.darkNavy};}@media(max-width:768px){.hs{grid-template-columns:1fr 1fr!important;}.ht{font-size:26px!important;}}`}</style>
      <div style={{background:C.white,borderBottom:"1.5px solid "+C.border,padding:"16px 40px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><a href="/" style={{display:"flex",alignItems:"center",gap:10,textDecoration:"none"}}><div style={{width:34,height:34,background:C.navy,borderRadius:6,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18}}>🏠</div><div><div style={{fontFamily:"'DM Serif Display',serif",fontSize:18,color:C.darkNavy}}>TaxAppeal USA</div><div style={{fontSize:9,textTransform:"uppercase",letterSpacing:"1.5px",color:C.mutedGray}}>Property Tax Dispute</div></div></a><button className="btn" style={{padding:"10px 22px",fontSize:14}} onClick={go}>Start my appeal</button></div>
      <section style={{background:C.navy,padding:"64px 40px",color:C.white}}><div style={{maxWidth:900,margin:"0 auto"}}><div style={{fontSize:12,color:C.gold,textTransform:"uppercase",letterSpacing:"2px",marginBottom:16}}>Fayetteville, Arkansas</div><h1 className="ht" style={{fontFamily:"'DM Serif Display',serif",fontSize:42,lineHeight:1.15,marginBottom:16}}>Fayetteville Property Tax Appeal — $89 Flat Fee</h1><p style={{fontSize:18,color:"#8596AF",lineHeight:1.6,maxWidth:640,marginBottom:32}}>Fayetteville is home to the University of Arkansas and one of the most active real estate markets in the state. Washington County assessments frequently outpace actual market values during cooling periods — making the August Board of Equalization appeal window a valuable opportunity.</p><div className="hs" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",gap:16,marginBottom:32}}>{[["Aug 17","2026 Deadline"],["0%","Of your savings taken"],["$89","Flat fee"],["Washington County","Service area"]].map(([n,l]) => (<div key={l} style={{background:"#0F1F3D",borderRadius:10,padding:16,textAlign:"center"}}><div style={{fontFamily:"'DM Serif Display',serif",fontSize:n.length>8?14:28,color:C.gold}}>{n}</div><div style={{fontSize:11,color:"#5A7A9F",marginTop:4}}>{l}</div></div>))}</div><button className="btn" style={{background:C.gold,color:C.darkNavy,fontSize:17,padding:"18px 44px"}} onClick={go}>File My Fayetteville Appeal — $89</button><div style={{fontSize:13,color:"#5A7A9F",marginTop:12}}>Takes about 4 minutes. Won't be charged until your letter is ready.</div></div></section>
      <section style={{padding:"24px 40px",background:"#FFF8E6",borderBottom:"1.5px solid #FFD97A"}}><div style={{maxWidth:800,margin:"0 auto",display:"flex",alignItems:"center",gap:16}}><div style={{fontSize:28}}>📅</div><div><div style={{fontWeight:700,fontSize:16,color:C.darkNavy}}>2026 Deadline: August 17 — Washington County Board of Equalization</div><div style={{fontSize:14,color:C.bodyGray,marginTop:4}}>Per Arkansas Code §26-27-317, your appeal must be postmarked by the third Monday in August. TaxAppeal files via USPS certified mail. Orders close August 10.</div></div></div></section>
      <section style={{padding:"56px 40px",background:C.white}}><div style={{maxWidth:800,margin:"0 auto"}}><h2 style={{fontFamily:"'DM Serif Display',serif",fontSize:30,textAlign:"center",marginBottom:12}}>Why Fayetteville Homeowners Should Appeal</h2><p style={{fontSize:15,color:C.bodyGray,textAlign:"center",marginBottom:36,lineHeight:1.7}}>Washington County home values rose sharply between 2020 and 2023 driven by university demand and remote work migration. Since then the market has cooled, but assessments often take time to reflect corrections — creating gaps between assessed value and actual market value that comparable sales evidence can close.</p><div style={{display:"grid",gap:24}}>{[["📊","Arkansas Assesses at 20% of Market Value","If your home's market value is overstated by Washington County, your assessed value (20% of market) is inflated by the same percentage — and so is your tax bill."],["📅","The August 17 Deadline Is Firm","Arkansas has one fixed statewide deadline: the third Monday in August. Miss it and you wait a full year. TaxAppeal files early via USPS certified mail."],["⚖️","No Percentage Fees — Ever","Most Arkansas consultants charge 25-40% of savings. On a $1,000 reduction that's up to $400 gone. TaxAppeal charges $89 flat."]].map(([icon,title,desc]) => (<div key={title} style={{display:"flex",gap:16}}><div style={{width:44,height:44,background:C.lightBlue,borderRadius:10,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,flexShrink:0}}>{icon}</div><div><h3 style={{fontSize:17,fontWeight:500,marginBottom:6}}>{title}</h3><p style={{fontSize:14,color:C.bodyGray,lineHeight:1.7}}>{desc}</p></div></div>))}</div></div></section>
      <section style={{padding:"56px 40px",background:C.lightBlue}}><div style={{maxWidth:800,margin:"0 auto"}}><h2 style={{fontFamily:"'DM Serif Display',serif",fontSize:30,textAlign:"center",marginBottom:10}}>How TaxAppeal Works in Fayetteville</h2><p style={{fontSize:15,color:C.bodyGray,textAlign:"center",marginBottom:36}}>Four minutes of your time. You sign it, we do the rest.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:20}}>{[["1","Enter your address","We pull your Washington County property data — assessed value, square footage, year built, and comparable sales."],["2","We build your case","Our system generates a professional appeal letter citing Arkansas Code §26-27-317 and §26-26-1901 with comparable sales from your area."],["3","We file via certified mail","Your appeal is mailed to the Washington County Board of Equalization secretary via USPS certified mail before August 17."]].map(([n,t,d]) => (<div key={n} style={{background:C.white,borderRadius:12,padding:24,border:"1.5px solid "+C.border}}><div style={{width:34,height:34,background:C.navy,borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:500,color:C.white,marginBottom:14}}>{n}</div><h3 style={{fontSize:15,fontWeight:500,marginBottom:8}}>{t}</h3><p style={{fontSize:13,color:C.bodyGray,lineHeight:1.65}}>{d}</p></div>))}</div></div></section>
      <section style={{padding:"56px 40px",background:C.lightBlue}}><div style={{maxWidth:720,margin:"0 auto"}}><h2 style={{fontFamily:"'DM Serif Display',serif",fontSize:28,textAlign:"center",marginBottom:36}}>Common Questions — Fayetteville Property Tax Appeals</h2><div style={{display:"flex",flexDirection:"column",gap:10}}>{faqs.map(([q,a],i) => (<div key={i} style={{background:C.white,border:"1.5px solid "+(openFaq===i?C.navy:C.border),borderRadius:10,overflow:"hidden"}}><div style={{padding:"16px 20px",fontSize:15,fontWeight:500,cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"center"}} onClick={()=>setOpenFaq(openFaq===i?null:i)}>{q}<span style={{fontSize:16,color:C.mutedGray}}>▾</span></div>{openFaq===i && <div style={{padding:"0 20px 16px",fontSize:14,color:C.bodyGray,lineHeight:1.7}}>{a}</div>}</div>))}</div></div></section>
      <div style={{background:C.navy,padding:"64px 40px",textAlign:"center"}}><h2 style={{fontFamily:"'DM Serif Display',serif",fontSize:34,color:C.white,marginBottom:12}}>File Before August 17, 2026</h2><p style={{fontSize:15,color:C.mutedGray,marginBottom:28}}>Don't miss the Washington County Board of Equalization deadline. You sign it, we file it — $89 flat.</p><button style={{background:C.gold,color:C.darkNavy,border:"none",borderRadius:8,padding:"18px 44px",fontSize:17,fontWeight:500,cursor:"pointer"}} onClick={go}>Start My Fayetteville Appeal — $89</button></div>
      <footer style={{background:C.darkNavy,padding:"24px 40px",textAlign:"center"}}><p style={{fontSize:13,color:C.mutedGray,lineHeight:1.8}}>© 2026 TaxAppeal USA · <a href="mailto:customerservice@taxappealusa.com" style={{color:C.mutedGray}}>customerservice@taxappealusa.com</a></p><p style={{fontSize:13,color:C.mutedGray}}>Serving Washington County, Arkansas · Deadline: August 17, 2026 · Arkansas Code §26-27-317</p><p style={{marginTop:8,fontSize:13}}><a href="/" style={{color:C.mutedGray,marginRight:16}}>Home</a><a href="/arkansas" style={{color:C.mutedGray,marginRight:16}}>Arkansas</a><a href="/terms" style={{color:C.mutedGray,marginRight:16}}>Terms</a><a href="/privacy" style={{color:C.mutedGray}}>Privacy</a></p></footer>
    </>
  );
}
